### ISSUE TITLE
Make metric_resolution configurable

### ISSUE THREAD

**Issue by simon3z** [openshift/origin-metrics#101]
Heapster can be launched with the`metric_resolution` (samples interval) option.

It would be nice to expose this option in the deployer.

cc @mwringe

**Comment by simon3z** [comment]
@mwringe any news on this one?

**Comment by jcantrill** [comment]
ref: https://github.com/openshift/origin-metrics/issues/101

**Comment by mwringe** [comment]
@jcantrill the update is that I am waiting for a LGTM on the pr I submitted :)

**Comment by mwringe** [comment]
This has since been merged in master and will be available in the next origin-metrics release.
