### ISSUE TITLE
Decide on a proper name for the deployer 

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin-metrics#102]
Should it be deployer or deployment:

origin-logging-deployment

metrics calls it:

openshift/origin-metrics-deployer

ref: https://github.com/openshift/origin-aggregated-logging/issues/108

**Comment by mwringe** [comment]
I viewed it as:
deployer: something which deploys something
deployment: something on which the act of deploying occurs

so +1 for deployer from me :)

**Comment by jcantrill** [comment]
@sosiouxme  seems we have settled on 'deployer' based on your logging changes, which works form

**Comment by mwringe** [comment]
Closing as it looks like we are settling on 'deployer'
