### ISSUE TITLE
Redirection on / loops on Internet Explorer

### ISSUE THREAD

**Issue by akram** [openshift/origin-metrics#104]
When trying to access https://metrics.paas.mycompany.com/ using Internet Explorer on Windows 8, we are facing a infinite redirect:
Probably linked to this issue: http://stackoverflow.com/questions/522353/meta-refresh-doesnt-work

**Comment by mwringe** [comment]
We also need to remove the reference to the old 0.7.0-SNAPSHOT in there, its not actually running that version.

I have no idea why IE is performing an infinite redirect, but I have stopped being surprised with how IE behaves sometimes

**Comment by jcantrill** [comment]
@jwforres have you seen this problem?

**Comment by jwforres** [comment]
@akram do you mean directly going to the metrics dashboard in the browser, or do you mean the openshift console making requests to the metrics API?

**Comment by jcantrill** [comment]
@akram What version of IE are you using.  @mwringe I presume this is a route to the hawkular UI?  Does it make use of a meta refresh?

**Comment by mwringe** [comment]
Some information about this issue: it doesn't affect the console  and it doesn't affect the rest api in anyway.

This deals specifically with accessing the '/' endpoint in Hawkular Metrics which should redirect to the splash page at '/hawkular/metrics' (and it appears to only affect IE based browsers). This is also not a page that we would expect a user to be accessing anyways (unless they want to see the awesome Hawkular Logo).

This is of course an issue that we need to resolve (along with the erroneous reference to the version). But it is not a high priority issue that breaks functionality in anyway.

**Comment by akram** [comment]
@jcantrill @jwforres , this is like @mwringe said, it only affects try to get / on the metrics URL.
It is a version of IE provided with windows 8 found at a customer. I don't know the exact version.

**Comment by jsanda** [comment]
I am going to close this issue since it has not had any recent activity. Please feel free to reopen if your issue is unresolved.
