### ISSUE TITLE
Improve tagging process

### ISSUE THREAD

**Issue by mwringe** [openshift/origin-metrics#110]
There are a lot of different places where we have the version of the component within a template. Currently this means we have to go through and update the templates with the latest version, commit the new templates, tag that commit, and then revert back to our previous template.

**Comment by jcantrill** [comment]
@mwringe  do we still have this issue with the latest release scripts used by @smarterclayton ?  I thought we had a discussion and determined this tag, commit, revert process was unnecessary.

**Comment by mwringe** [comment]
Closing - no longer needed.
