### ISSUE TITLE
Add cli debug options to the Hawkular Metrics container

### ISSUE THREAD

**Issue by mwringe** [openshift/origin-metrics#115]
There are certain situations where we may need to inspect information from the Hawkular Metrics server itself. Currently this requires asking users to run a complex curl command, which is less than ideal.

It would be great to give them the ability to run a simple cli from on the container which allows them to more easily debug information.

**Comment by burmanm** [comment]
I think modifying the hawkular-client-python would be quite suitable as it provides quite a simple way of interacting with the metrics server. Currently the REPL process would be:

```python
>>> from hawkular import metrics
>> client = metrics.HawkularMetricsClient(tenant_id='admin')
>>> namespaces = client.query_tenants()
>>> for namespace in namespaces:
..   print('{}'.format(namespace['id']))
... 
0edf83ae-037a-47b8-8e17-3ad22bd832ba
8ffad5d3-add4-4363-96ef-89e80732258e
e2de7fae-3898-40ac-9566-24251ac47033
019bced8-b586-448c-9d48-3b0f06947f8c
d8c49526-beb0-4f8b-8fb0-875894d8c526
>>>
>>> client.create_gauge_definition('example.metric.1', dataRetention=90, units='bytes', hostname='localhost')
True
>>> client.query_definitions(metrics.MetricType.Gauge)
[{'tenantId': 'admin', 'dataRetention': 90, 'id': 'example.metric.1', 'tags': {'hostname': 'localhost', 'units': 'bytes'}, 'type': 'gauge'}]
>>>
```

We could write a small wrapper around the python client to allow automatic connection to the instance and provide pretty printing out of the box.

**Comment by mwringe** [comment]
Yeah, I am thinking along the lines of a small wrapper to be able to do some simple commands. The user would then just exec into the container (or use the terminal access from the console) to access it.

Really what I am trying to do here is allow a user to simply check if certain metrics are being stored or not so that they can rule out issues in the router or in the console

**Comment by burmanm** [comment]
Then I think the wrapper + python client would be a suitable solution. It would allow using simple commands to detect if a metric is being stored, as well as allow in theory to execute more complicated requests if support needs more debugging info.

I need to do couple of changes to the python-client to support this scenario (such as SSL support) and I can then create some example wrapper to help in defining the requirements / ease of use.

**Comment by jcantrill** [comment]
@mwringe  Is this something that should be an 'oc metrcis...' something command.  @sosiouxme  has mentioned wanting something for logging.  Would this make more sense to add to our metrics diagnostics?

**Comment by mwringe** [comment]
@jcantrill there are some problems where we need to verify if Hawkular Metrics has received metrics and is continuing to receive metrics. Currently we have to ask users to do some curl commands to verify these things, it would be much easier if a user could just exec (or use the terminal from the console) to run some more simplified commands without having to resort to awkward curl commands.

**Comment by jcantrill** [comment]
@mwringe I believe the config written by the CLI has the ability to save 'custom' key/value pairs.  It would be interesting to add a oc metrics command(s) that just knew where metrics lived and could provide the info you suggest.

**Comment by mwringe** [comment]
@burmanm are you still looking into this?

**Comment by burmanm** [comment]
@mwringe Yes, I'm just slightly more occupied with some changes to HWKMETRICS and clients.

**Comment by mwringe** [comment]
@burmanm awesome, thanks
