### ISSUE TITLE
failed to enable cluster metrics, the Heapster pod always not ready

### ISSUE THREAD

**Issue by tj13** [openshift/origin-metrics#123]
the container log as below:

Endpoint Check in effect. Checking https://hawkular-metrics:443/hawkular/metrics/status
Could not connect to https://hawkular-metrics:443/hawkular/metrics/status. Curl exit code: 28. Status Code 000
'https://hawkular-metrics:443/hawkular/metrics/status' is not accessible [HTTP status code: 000. Curl exit code 28]. Retrying.
Could not connect to https://hawkular-metrics:443/hawkular/metrics/status. Curl exit code: 28. Status Code 000

# oc get pods
oc NAME                         READY     STATUS             RESTARTS   AGE
hawkular-cassandra-1-nf9go   1/1       Running            0          17m
hawkular-metrics-tm1h6       1/1       Running            0          16m
heapster-s176f               0/1       CrashLoopBackOff   5          17m
metrics-deployer-trleg       1/1       Running            0          17m

# oc describe pod heapster-s176f 
Name:heapster-s176f
Namespace:openshift-infra
Node:centosdev02.example.com/172.0.27.8
Start Time:Tue, 24 May 2016 15:18:31 +0800
Labels:metrics-infra=heapster,name=heapster
Status:Running
IP:10.1.0.5
Controllers:ReplicationController/heapster
Containers:
  heapster:
    Container ID:docker://85d74d35cf498934233cc43cd5f9e004185dc19bc1448a3d7cb66ea224713e33
    Image:openshift/origin-metrics-heapster:latest
    Image ID:docker://cdcb32f9b621b544ed319c996fd8b07eda2956c5a4bdcec4bfd6a031616369ad
    Port:8082/TCP
    Command:
      heapster-wrapper.sh
      --wrapper.username_file=/hawkular-account/hawkular-metrics.username
      --wrapper.password_file=/hawkular-account/hawkular-metrics.password
      --wrapper.allowed_users_file=/secrets/heapster.allowed-users
      --wrapper.endpoint_check=https://hawkular-metrics:443/hawkular/metrics/status
      --source=kubernetes:https://centosdev01.example.com:8443?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250
      --sink=hawkular:https://hawkular-metrics:443?tenant=_system&labelToTenant=pod_namespace&labelNodeId=nodename&caCert=/hawkular-cert/hawkular-metrics-ca.certificate&user=%username%&pass=%password%&filter=label(container_name:^system.slice.*|^user.slice)
      --tls_cert=/secrets/heapster.cert
      --tls_key=/secrets/heapster.key
      --tls_client_ca=/secrets/heapster.client-ca
      --allowed_users=%allowed_users%
      --metric_resolution=10s
    QoS Tier:
      memory:BestEffort
      cpu:BestEffort
    State:Waiting
      Reason:CrashLoopBackOff
    Last State:Terminated
      Reason:Error
      Exit Code:1
      Started:Tue, 24 May 2016 15:31:59 +0800
      Finished:Tue, 24 May 2016 15:34:00 +0800
    Ready:False
    Restart Count:5
    Readiness:exec [/opt/heapster-readiness.sh] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment Variables:
Conditions:
  TypeStatus
  Ready False 
Volumes:
  heapster-secrets:
    Type:Secret (a volume populated by a Secret)
    SecretName:heapster-secrets
  hawkular-metrics-certificate:
    Type:Secret (a volume populated by a Secret)
    SecretName:hawkular-metrics-certificate
  hawkular-metrics-account:
    Type:Secret (a volume populated by a Secret)
    SecretName:hawkular-metrics-account
  heapster-token-bybvx:
    Type:Secret (a volume populated by a Secret)
    SecretName:heapster-token-bybvx
Events:
  FirstSeenLastSeenCountFromSubobjectPathTypeReasonMessage
  ------------------------------------------------------------
  17m17m1{default-scheduler }NormalScheduledSuccessfully assigned heapster-s176f to centosdev02.example.com
  17m17m1{kubelet centosdev02.example.com}spec.containers{heapster}NormalCreatedCreated container with docker id 8689ab9615d9
  17m17m1{kubelet centosdev02.example.com}spec.containers{heapster}NormalStartedStarted container with docker id 8689ab9615d9
  15m15m1{kubelet centosdev02.example.com}spec.containers{heapster}NormalStartedStarted container with docker id ec4d6cf9e544
  15m15m1{kubelet centosdev02.example.com}spec.containers{heapster}NormalCreatedCreated container with docker id ec4d6cf9e544
  12m12m1{kubelet centosdev02.example.com}WarningFailedSyncError syncing pod, skipping: failed to "StartContainer" for "heapster" with CrashLoopBackOff: "Back-off 10s restarting failed container=heapster pod=heapster-s176f_openshift-infra(b7febd7f-217f-11e6-ba8c-0699f0f3903c)"

  12m12m1{kubelet centosdev02.example.com}spec.containers{heapster}NormalCreatedCreated container with docker id 808bcb169a5e
  12m12m1{kubelet centosdev02.example.com}spec.containers{heapster}NormalStartedStarted container with docker id 808bcb169a5e
  10m10m2{kubelet centosdev02.example.com}WarningFailedSyncError syncing pod, skipping: failed to "StartContainer" for "heapster" with CrashLoopBackOff: "Back-off 20s restarting failed container=heapster pod=heapster-s176f_openshift-infra(b7febd7f-217f-11e6-ba8c-0699f0f3903c)"

  10m10m1{kubelet centosdev02.example.com}spec.containers{heapster}NormalStartedStarted container with docker id 8c8488aa21be
  10m10m1{kubelet centosdev02.example.com}spec.containers{heapster}NormalCreatedCreated container with docker id 8c8488aa21be
  8m7m3{kubelet centosdev02.example.com}WarningFailedSyncError syncing pod, skipping: failed to "StartContainer" for "heapster" with CrashLoopBackOff: "Back-off 40s restarting failed container=heapster pod=heapster-s176f_openshift-infra(b7febd7f-217f-11e6-ba8c-0699f0f3903c)"

  7m7m1{kubelet centosdev02.example.com}spec.containers{heapster}NormalStartedStarted container with docker id 09c7217f649b
  7m7m1{kubelet centosdev02.example.com}spec.containers{heapster}NormalCreatedCreated container with docker id 09c7217f649b
  5m4m6{kubelet centosdev02.example.com}WarningFailedSyncError syncing pod, skipping: failed to "StartContainer" for "heapster" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=heapster pod=heapster-s176f_openshift-infra(b7febd7f-217f-11e6-ba8c-0699f0f3903c)"

  17m3m6{kubelet centosdev02.example.com}spec.containers{heapster}NormalPullingpulling image "openshift/origin-metrics-heapster:latest"
  17m3m6{kubelet centosdev02.example.com}spec.containers{heapster}NormalPulledSuccessfully pulled image "openshift/origin-metrics-heapster:latest"
  3m3m1{kubelet centosdev02.example.com}spec.containers{heapster}NormalStartedStarted container with docker id 85d74d35cf49
  3m3m1{kubelet centosdev02.example.com}spec.containers{heapster}NormalCreatedCreated container with docker id 85d74d35cf49
  17m1m74{kubelet centosdev02.example.com}spec.containers{heapster}WarningUnhealthyReadiness probe failed: The heapster process is not yet started, it is waiting for the Hawkular Metrics to start.

  12m10s21{kubelet centosdev02.example.com}spec.containers{heapster}WarningBackOffBack-off restarting failed docker container
  1m10s9{kubelet centosdev02.example.com}WarningFailedSyncError syncing pod, skipping: failed to "StartContainer" for "heapster" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=heapster pod=heapster-s176f_openshift-infra(b7febd7f-217f-11e6-ba8c-0699f0f3903c)"

＃oc version
oc v1.2.0-rc1
kubernetes v1.2.0-36-g4a3f9c5

**Comment by tj13** [comment]
Endpoint Check in effect. Checking https://hawkular-metrics:443/hawkular/metrics/status
Could not connect to https://hawkular-metrics:443/hawkular/metrics/status. Curl exit code: 28. Status Code 000
'https://hawkular-metrics:443/hawkular/metrics/status' is not accessible [HTTP status code: 000. Curl exit code 28]. Retrying.

is it possible to custom the Enpoint URL. it's https://hawkular-metrics:8443/hawkular/metrics/status for this case. how i can change it?

**Comment by mwringe** [comment]
The 'hawkular-metrics' hostname is resolved using the service name resolution from the OpenShift DNS server, its not configurable and is not meant to be configurable.

The curl exit code 28 means that it encountered a timeout trying to access this endpoint. Are you able to access the endpoint directly using the service ip address instead of the 'hawkular-metrics' hostname?

**Comment by tj13** [comment]
$ oc get svc
NAME                       CLUSTER-IP       EXTERNAL-IP   PORT(S)                               AGE
hawkular-cassandra         172.30.162.92    <none>        9042/TCP,9160/TCP,7000/TCP,7001/TCP   5m
hawkular-cassandra-nodes   None             <none>        9042/TCP,9160/TCP,7000/TCP,7001/TCP   5m
hawkular-metrics           172.30.167.196   <none>        443/TCP                               5m
heapster                   172.30.76.149    <none>        80/TCP                                5m

$ telnet 172.30.167.196 443
Trying 172.30.167.196...
Connected to 172.30.167.196.
Escape character is '^]'.
^]quit

telnet> quit
Connection closed.

[tanjun@centosdev01 origin-metrics]$ oc project
Using project "openshift-infra" on server "https://centosdev01.sit.caijj.net:8443".
$ curl -X GET https://172.30.167.196/hawkular/metrics/status
^C
$ curl -v -X GET https://172.30.167.196/hawkular/metrics/status
* About to connect() to 172.30.167.196 port 443 (#0)
*   Trying 172.30.167.196...
* Connected to 172.30.167.196 (172.30.167.196) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none

it's very strange, telnet is successfully, but failed for curl.

**Comment by tj13** [comment]
the router status is healthy, so i guess the hawkular-metrics	is deployed successfully. 
<img width="1302" alt="2016-05-24 9 23 58" src="https://cloud.githubusercontent.com/assets/14867953/15505448/35922734-21f6-11e6-9e97-fa36ed6ba9d9.png">
<img width="914" alt="2016-05-24 9 25 21" src="https://cloud.githubusercontent.com/assets/14867953/15505455/3d6ca434-21f6-11e6-8ea7-fc9fa69c930e.png">

**Comment by tj13** [comment]
it looks like access from the route is successful.
[tanjun@centosdev01 origin-metrics]$ curl -k -X GET https://hawkular-metrics.apps.sit.caijj.net:8443/hawkular/metrics/status
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:anonymous\" cannot \"get\" on \"/hawkular/metrics/status\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}

**Comment by mwringe** [comment]
Can you exec into the pod running Hawkular Metrics and try to access the /hawkular/metrics/status endpoint using 'localhost' as well as 'hawkular-metrics'? If you cannot access the hawkular-metrics hostname, then there is something wrong with your setup. This could be due to the OpenShift DNS server not running properly, or perhaps a firewall rule or something preventing access on your system.

**Comment by tj13** [comment]
running below commands inside Hawkular Metrics container both succefully.

bash-4.2$ curl -k https://localhost:8443/hawkular/metrics/status 
{"MetricsService":"STARTED","Implementation-Version":"0.15.0.Final","Built-From-Git-SHA1":"6731208d7eacbf3ffd102c21943214a51384f390"}

bash-4.2$ curl -k https://172.30.167.196:443/hawkular/metrics/status
{"MetricsService":"STARTED","Implementation-Version":"0.15.0.Final","Built-From-Git-SHA1":"6731208d7eacbf3ffd102c21943214a51384f390"}

but it failed when accessing Hawkular Metrics from the nodes except Hawkular Metrics besides on. 

telnet and dig both successfully, so DNS and firewall should fine. 

tanjun@centosdev01 ~]$ curl  -m 5 -v -k https://172.30.167.196:443/hawkular/metrics/status
* About to connect() to 172.30.167.196 port 443 (#0)
*   Trying 172.30.167.196...
* Connected to 172.30.167.196 (172.30.167.196) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* Operation timed out after 5001 milliseconds with 0 out of 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 5001 milliseconds with 0 out of 0 bytes received
[tanjun@centosdev01 ~]$ telnet 172.30.167.196 443
Trying 172.30.167.196...
Connected to 172.30.167.196.
Escape character is '^]'.
^]quit

telnet> quit
Connection closed.
[tanjun@centosdev01 ~]$ dig @172.0.27.7 +short  kubernetes.default.svc.cluster.local
172.30.0.1

should i run all these component one single node?

**Comment by tj13** [comment]
deployment finally succeed after pin all the components on single node. but still can not get the metrics for pods on web console.
<img width="912" alt="2016-05-24 11 44 52" src="https://cloud.githubusercontent.com/assets/14867953/15510358/8b97da62-2209-11e6-9566-4285b0c4850d.png">

and one more question is metrics should be accessed via HAWKULAR_METRICS_HOSTNAME through the router( listen on 443), or directly by openshift (listen 8443)?.

**Comment by mwringe** [comment]
You shouldn't have to put everything on one node. It sounds like your environment is not properly configured. Are you blocking port access between nodes with a firewall?

You should be able to access https://${HAWKULAR_METRICS_HOSTNAME} directly in a browser, that is what the console is going to be using.

**Comment by tj13** [comment]
so wierd issue. 
i'll re-deploy the whole openshift cluster.
how can i install enable the cluster metrics during the openshift installation?

**Comment by ekuric** [comment]
@tj13 I think I had same/similar issue and it was caused by misspelled metricsPublicURL in master-config.yaml file, can you check it in your configuration and ensure it is 

```
metricsPublicURL
```
and not misspelled to something else
/cc @mwringe

**Comment by tj13** [comment]
@ekuric  
the configuration is correct. 
metricsPublicURL: https://hawkular-metrics.apps.sit.caijj.net/hawkular/metrics
which is same as the route on the web console.

access service ip is successfully on the node which HAWKULAR_METRICS resides on, but failed on the other nodes. 

i've already delete ALL the REJECT iptable rules on INPUT chain.

**Comment by tj13** [comment]
issue got fixed finally.  two key points;
1. force all hawkular metrics components run on single node
2. add parameter --host-network=false when deploying the router

**Comment by mwringe** [comment]
You really should not have to force any of the components to be running on the same node, they should be able to run on any node in your cluster. I would suspect something is wrong with the network connections between your nodes in this case.
