### ISSUE TITLE
cassandra cluster nodes does not follow cassandra pods scale down 

### ISSUE THREAD

**Issue by ekuric** [openshift/origin-metrics#141]
casssandra nodes number will not reflect pods after scale up down. 

Scale cassandra pods to 3 using 
`$ for m in $(seq 2 3); do oc process -n openshift-infra hawkular-cassandra-node-emptydir NODE=$m  | oc create -n openshift-infra -f - ;done`

let pods to form cassandra cluster. Check cassandra cluster 

```
$ nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns    Host ID                               Rack
UN  10.1.1.16  8.9 MB     256          ?       ada88437-63dd-41d8-b8a9-450c459420ff  rack1
UN  10.1.2.2   27.49 MB   256          ?       9f534855-fb12-4372-80c3-41b8e44d89d2  rack1
UN  10.1.0.15  13.32 MB   256          ?       2e58a518-bb5a-40af-979d-b3d687340e3a  rack1
```

in this status , metrics via web openshift interface will work fine. 

Downsize number of cassandra pods with 
`oc delete rc -n openshift-infra hawkular-cassandra-2 hawkular-cassandra-3`
check status of cassandra cluster 

```
# oc get rc -n openshift-infra
NAME                   DESIRED   CURRENT   AGE
hawkular-cassandra-1   1         1         22h
hawkular-metrics       1         1         22h
heapster               1         1         22h
root@ip-172-31-53-193: ~ # oc rsh -n openshift-infra hawkular-cassandra-1-xu7wl
sh-4.2$ nodetool status 
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns    Host ID                               Rack
DN  10.1.1.16  8.9 MB     256          ?       ada88437-63dd-41d8-b8a9-450c459420ff  rack1
UN  10.1.2.2   27.13 MB   256          ?       9f534855-fb12-4372-80c3-41b8e44d89d2  rack1
DN  10.1.0.15  13.32 MB   256          ?       2e58a518-bb5a-40af-979d-b3d687340e3a  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```

even pods are deleted, cassadnra cluster still have record for these deleted nodes 

check metrics via web interface, it will report issue as 

```
Metrics are not available.

An error occurred getting metrics for container helloworld from https://hostname.my.master.com/hawkular/metrics.
If you have network connectivity, this could indicate a misconfiguration.
Please contact your system administrator.

Failed to perform operation due to an error: All host(s) tried for query failed (tried: hawkular-cassandra/172.30.72.223:9042 (com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency LOCAL_ONE (1 required but only 0 alive))) 
```

remove nodes in DN state 

```
nodetool removenode  ada88437-63dd-41d8-b8a9-450c459420f 
```

```
$ nodetool status                                    
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address   Load       Tokens       Owns    Host ID                               Rack
UN  10.1.2.2  27.13 MB   256          ?       9f534855-fb12-4372-80c3-41b8e44d89d2  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```

metrics will be again available with gaps on graphs for time affected with above issue when cassandra nodes were node removed from cassandra cluster.

**Comment by mwringe** [comment]
you cannot just delete the rc to downsize a Cassandra cluster.

You need to exec into the pod and run 'nodetool decommission', once this is completed then you remove the rc

**Comment by timothysc** [comment]
Can't the pod be signaled and allowed to gracefully terminate via script wrapper?

**Comment by mwringe** [comment]
@timothysc last I really looked into it, I don't believe we could. There are two different termination types, one is if you are just wanting to restart the pod, and the other is if you are wanting to scale down the cluster size. if you want to scale down the cluster size, then you need to perform 'nodetool decomission' (which is not a cheap operation, essentially all the data stored in that node needs to be propagated to the other nodes in the cluster).

We should be moving to petsets in the future (once they are ready) which should make scaling up easier, but I think it still has the issue where you need to manually do something to scale things down.

**Comment by timothysc** [comment]
pet-sets is orthogonal to this.  This has to do with pod life-cycle hooks.  

/cc @smarterclayton

**Comment by mwringe** [comment]
Petsets are very much going to be a part of this as we are going to be moving the Cassandra scaling mechanism to pet sets when they become available. Thatever options we have there with regards to life cycle hooks will have to be considered when we move to them. We are currently limited to lifecycle hooks due to the work arounds we have to do currently.

As already mentioned, we cannot use life-cycle hooks for this. There is a difference between restarting a pod and resize a Cassandra cluster. But from the view of the pod, it can't know the difference.

**Comment by timothysc** [comment]
> There is a difference between restarting a pod and resize a Cassandra cluster.

well aware. 

Hmm if pet-sets had a (resize hook) that would probably solve this.  Lifecycle events for pet-sets would/should be unique to that resource type.

**Comment by smarterclayton** [comment]
Cluster reconfig hook is probably going to be part of graduation of pet
sets.

On Fri, Jun 10, 2016 at 5:00 PM, Timothy St. Clair <notifications@github.com

**Comment by mwringe** [comment]
The last I looked at petsets, they would allow automated scaling up, but they were not considering scaling down to be an automated process and would require an admin to manually do this. But its been a while and I hope we do have scale down hook that we can use.

What we currently have is less than optimal

**Comment by smarterclayton** [comment]
That's not true exactly, what we said was that we would err on the side of
safety.  Scaling down requiring admin intervention is a good thing.

**Comment by timothysc** [comment]
> Cluster reconfig hook is probably going to be part of graduation of pet-sets.

awesome.

**Comment by timothysc** [comment]
@ekuric re:your original comment, instead of trying to perform elastic-like operations we'll need to have well-thought recommendations along with notes on conditions for the time being. 

I'd still leave this open as a reminder for RFE on PetSets.

**Comment by chrislovecnm** [comment]
The signal API proposal I think is a feature set that will help with this use case. 

See here https://github.com/kubernetes/kubernetes/pull/26884
