### ISSUE TITLE
not able to access hawkular-metrics URL on port 443

### ISSUE THREAD

**Issue by priyanka5** [openshift/origin-metrics#142]
Hi, I am running origin version:
oc v1.1.6-3-g9c5694f
kubernetes v1.2.0-36-g4a3f9c5

I installed master on port 443 instead 8443 via Ansible. Router runs on master. Now I am trying to setup cluster metrics in "openshift-infra" , everything just works fine, But whenever I try to access hawkular-metrics URL, it redirects me to Master webconsole login page. I noticed hawkular metrics also runs on port 443 which might be the issue. So is there a way I can change port?? or how to resolve this , so that I can access hawkular metrics URL.

any help would be appreciated.

Thanks in advance.

@csrwng @bparees - tagging you guys if you can help here. 

P.S. - it works when I install master on 8443.

**Comment by bparees** [comment]
@priyanka5 this would be @jcantrill's area.

**Comment by mwringe** [comment]
You could change the Hawkular Metrics service to run on a different port (or change the route to use a different port). But we don't expose this as a configuration option in the deployer as it doesn't make a lot of sense. Individual services should be free to use whatever port they want as they run on different addresses.
Why is the Hawkular Metrics service set to use the same IP address as the master?

**Comment by priyanka5** [comment]
Hi @mwringe, thanks for the response I have already tried changing port in hawkular metrics service but it didn't work :( . I am exposing hawkular metrics on Hostname which points to public ip of machine where router is running. Here router and master both are deployed in same virtual machine. That's the region  hawkular metrics  uses same IP address as the master. Am I doing something wrong? Any help would be appreciated

**Comment by mwringe** [comment]
Changing the port for the Hawkular Metrics service will have the service use a different port (note: you need to change the 'port' values not the 'targetPort' value). What is not working for you when you do that exactly? Can you access the service directly using the service ip address and that port?

**Comment by priyanka5** [comment]
@mwringe : Attaching my hawkular metrics service yaml. I can access service directly using the service ip and changed port via curl, but if i expose it on hostname, again it redirects me to origin console. any help? 
[service.txt](https://github.com/openshift/origin-metrics/files/310299/service.txt)

**Comment by mwringe** [comment]
@bparees @jcantrill  this is not an issue with metrics and has to do with routing connections. Who should be responsible for this?

**Comment by bparees** [comment]
@mwringe you can try @knobunc (networking lead)
