### ISSUE TITLE
Leverage Inter-pod Anti-affinity on Cassandra pods.

### ISSUE THREAD

**Issue by timothysc** [openshift/origin-metrics#146]
For fault tolerance and disk utilization issues, the cassandra pods should aim to leverage inter-pod anti-affinity. 
https://github.com/kubernetes/kubernetes/blob/master/docs/design/podaffinity.md

In general this should almost be a requirement for Pet-Sets.

/cc @ekuric

**Comment by jpkrohling** [comment]
I could start looking into this one

**Comment by jpkrohling** [comment]
@timothysc , @ekuric , could you confirm whether this proposal has been implemented yet? Also, it's not clear to me where the anti-affinity would be configured. Is it at the service-level? I tried setting the anti affinity at service level, with the latest origin from master, but it seems this setting is currently being ignored.

**Comment by timothysc** [comment]
@jpkrohling It has but I would not rely on it until 3.4 as there have been a series of fixes that will likely not make 3.3.
