### ISSUE TITLE
Heapster not collecting metrics on docker-machine OS

### ISSUE THREAD

**Issue by csrwng** [openshift/origin-metrics#149]
On a Mac, after starting a cluster with 'oc cluster up' and installing metrics components, everything seems to be installed correctly and there's no errors in the logs. However, no metrics are collected.

It is possible that cAdvisor is not providing the correct stats.

**Comment by csrwng** [comment]
@mwringe

**Comment by mwringe** [comment]
How exactly is this being run on a mac?

**Comment by csrwng** [comment]
It's using docker machine for Mac, which runs Docker on a vm with Docker's own Linux distro: https://github.com/boot2docker/boot2docker

**Comment by jsanda** [comment]
I am going to close this issue since it has not had any recent activity. Please feel free to reopen if your issue is unresolved.
