### ISSUE TITLE
hawkul metrics not starting on provided hostname

### ISSUE THREAD

**Issue by priyanka5** [openshift/origin-metrics#151]
Hi , I have followed the steps from doc. It used to work fine. But now when I am creating it again after deleting everything. It doesn't listen on host provided with HAWKULAR_METRICS_HOSTNAME. 

In heapster logs it keeps giving:

'https://hawkular-metrics:443/hawkular/metrics/status' is not accessible [HTTP status code: 000. Curl exit code 7]. Retrying.
Could not connect to https://hawkular-metrics:443/hawkular/metrics/status. Curl exit code: 7. Status Code 000
'https://hawkular-metrics:443/hawkular/metrics/status' is not accessible [HTTP status code: 000. Curl exit code 7]. Retrying.

however I have not given this endpoint. I also checked DNS from https://github.com/openshift/origin-metrics/blob/master/docs/troubleshooting.adoc , it works fine. 

Is there something else needs to be done?

how to resolve this?

@mwringe any help? 

dont know what happens it was working fine before in other installation with same steps.

thanks

**Comment by mwringe** [comment]
What exact secrets and deployment options are you using to deploy this?

**Comment by priyanka5** [comment]
@mwringe : thanks for response, I followed exact steps from https://github.com/openshift/origin-metrics 

created secrets using: oc secrets new metrics-deployer nothing=/dev/null -n openshift-infra 

deployed using command with valid hostname only:

oc new-app -f metrics-deployer.yaml \
    -p HAWKULAR_METRICS_HOSTNAME=hawkular-metrics.--southeast-1.compute.amazonaws.com \
    -p USE_PERSISTENT_STORAGE=false

origin version:
oc v1.1.6-3-g9c5694f
kubernetes v1.2.0-36-g4a3f9c5

any help what could be the issue.

**Comment by priyanka5** [comment]
@jcantrill : thanks for pointing on the link, but my hostname is valid only which points to router ip.

**Comment by mwringe** [comment]
@priyanka5 if you are using origin metric, can you pull in the latest hawkular metrics image and try again? I just pushed out a newer Hawkular Metrics image which fixed an issue preventing it from starting.

If not, can you check the Hawkular Metrics logs and see if anything is in there?

**Comment by priyanka5** [comment]
@mwringe : thanks, I tried today with latest hawkular metrics image , it works fine , but in logs it shows:

E0617 09:25:16.681585       1 reflector.go:205] k8s.io/heapster/metrics/heapster.go:232: Failed to list *api.Pod: Get https://masterhost:8443/api/v1/pods?resourceVersion=0: x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, localhost, openshift, openshift.default, openshift.default.svc, openshift.default.svc.cluster.local, 127.0.0.1, not masterhost

is this the expected one?

**Comment by mwringe** [comment]
@priyanka5 I am assuming you have set MASTER_URL to be https://masterhost:8443.

Currently your master url is using an invalid certificate and Heapster is refusing to connect (which is the expected and desired behaviour). If you need to have this available under the 'masterhost' hostname, then the certificate for this needs to be valid for 'masterhost' which it currently is not.

The default value is https://kubernetes.default.svc:443 which if you look from your error message the certificate is valid for this.

Can you please try unsetting this value? Or explain why you had to set it?

**Comment by mwringe** [comment]
@priyanka5 There is a good section of the docs which goes over this with how to check and regenerate your certificates. Its meant as part of a manual update process from an old install, but I think most of it should still apply in your case: https://docs.openshift.org/latest/install_config/upgrading/manual_upgrades.html#manual-checking-the-masters-certificate

But is there a reason why you set the the MASTER_URL value? Have you tried not setting this and seeing if this fixes the problem? Your master can be resolved from multiple hostnames, and normally leaving it as default hostname of 'kubernetes.default.svc' should work
