### ISSUE TITLE
Typo on METRIC_DURATION metrics template parameter

### ISSUE THREAD

**Issue by Tomtom76** [openshift/origin-metrics#155]
hi

on page

https://github.com/openshift/origin-metrics#deploying-all-of-the-metrics-components

METRICS_DURATION is actually METRIC_DURATION

**Comment by mwringe** [comment]
Thanks for finding the typo.

Fixed with https://github.com/openshift/origin-metrics/pull/156 (may need to wait for a bit for the tests to run before the PR will be merged)
