### ISSUE TITLE
 cassandra load [ from nodetool status ] over time increases 

### ISSUE THREAD

**Issue by ekuric** [openshift/origin-metrics#163]
environment : 

```
atomic-openshift-sdn-ovs-3.2.1.3-1.git.0.dfa4ad6.el7.x86_64
atomic-openshift-3.2.1.3-1.git.0.dfa4ad6.el7.x86_64
atomic-openshift-master-3.2.1.3-1.git.0.dfa4ad6.el7.x86_64
tuned-profiles-atomic-openshift-node-3.2.1.3-1.git.0.dfa4ad6.el7.x86_64
atomic-openshift-node-3.2.1.3-1.git.0.dfa4ad6.el7.x86_64
atomic-openshift-clients-3.2.1.3-1.git.0.dfa4ad6.el7.x86_64
docker-common-1.9.1-40.el7.x86_64
docker-forward-journald-1.9.1-40.el7.x86_64
docker-selinux-1.9.1-40.el7.x86_64
docker-1.9.1-40.el7.x86_64
```

metrics images 

```
docker.io/openshift/origin-metrics-cassandra                     latest              5a50d0bf7d01 
docker.io/openshift/origin-metrics-hawkular-metrics        latest              0b79428cc1f9
docker.io/openshift/origin-metrics-heapster                      latest              3b6697a31120
docker.io/openshift/origin-metrics-deployer                      latest              9bc2a6937fd7
```

I was monitoring 1000 pods across 10 OSE nodes and collecting 

```
$ nodetool status 
```

every minute for 7 hours ( doing now 24 hours ) and I see linear increase inside cassandra pod over time. Here is graph ( test was running 420 minutes  ) 
![cassandra_load_vs_time](https://cloud.githubusercontent.com/assets/1200198/16418304/7ef4f6f4-3d49-11e6-9975-4ef7427633be.png)

additional notes 
- Number pods were not changed over time ( 1000 pods were monitored ).
- When metrics started to monitor pods, load ( here load means column "Load" in nodetool status output ) was round 54 MB, after 7h it went up to 1 GB 
- persistant volume is used for metrics, but pv was not used previously for metrics - it was new PV, not used previously 
- this correspond approximately size in `/cassandra_data/data` eg 

```
$ nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  172.20.4.2  800.18 MB  256          ?       51d447d9-ab54-4a9a-b329-84455040f823  rack1

$ pwd 
cassandra_data

$ du -h . | grep data | tail -3
0   ./data/hawkular_metrics/sys_config-db40b2c03d0511e698eadf0212d6e552
829M    ./data/hawkular_metrics
830M    ./data
```

Is this normal behavior for cassandra used in metrics environment? This can lead that space on /data is filled and metrics will stop working

**Comment by mwringe** [comment]
I am not entirely sure what you are asking here.

Cassandra is a database, and as more and more data is written to it, it will increase the amount of disk space being used. It does not infinitely increase in disk size though. Hawkular Metrics puts a TTL on the metric data, and once that TTL period has elapsed, the old data will be removed to make way for the new data. At this point, the disk size usage should stabilise and level out.

By default this TTL is 7 days and is configurable with the METRIC_DURATION deployer parameter

**Comment by timothysc** [comment]
For time series data on a relatively small data-set he's showing that we're going to be in trouble @ larger scales.  

It also shows that we're not really efficiently collecting time-series data.   

Our goal is 200,000 - 1,000,000 pods.  So if you back of the envelope calculate (1000-54)/7 = 135.14 MB/hour for 1000 pods.  or .1314 MB/hour per pod.  

Now take that basic number and multiply it out:   .1351 *1,000,000*(7*24) = 22696800 MB or 22.69TB 

So we need to do something here: 

- Change Defaults (sampling interval + duration)
- More efficiently collect time series data 
...

**Comment by sosiouxme** [comment]
Another possibility might be storing the data so that older data thins out over time a la https://en.wikipedia.org/wiki/RRDtool - you're not generally interested in maintaining the same granularity on data from a day ago as in the last hour.

**Comment by mwringe** [comment]
yeah, we will most likely have to change how data is stored so that we only just store what is needed for the console. I created trello card for this this morning: https://trello.com/c/d1CHq8OB/322-only-store-metrics-needed-for-console-metrics

But this starts to get into some tricky storage schemas, and I don't know when Hawkular Metrics will be able to do something like this.

I have been requesting having Hawkular Metrics work more like a circular buffer, but its not something that Cassandra can support. This would solve our out of disk issues as well

**Comment by timothysc** [comment]
> But this starts to get into some tricky storage schemas, and I don't know when Hawkular Metrics will be able to do something like this.

There are a number of strategies to run compaction on time series data.  Most time series DB's have them built in, in some way.

**Comment by ekuric** [comment]
On the graph below you can see cassandra load development over 24h for case when 1000 pods were monitored.Here cassanra load value was collected every minute from inside cassandra pod using 

``` $ nodetool status```  

command. Graph is below 

![24h_cassandra_load_1000pods](https://cloud.githubusercontent.com/assets/1200198/16555854/1143dbec-41d7-11e6-97e7-88719be675e1.png)

**Comment by burmanm** [comment]
@sosiouxme @mwringe Reduction of resolution (which is what for example RRDTool does and also the predecessor of Hawkular, RHQ - with Cassandra) is not magical and there's nothing in the current storage schema that would prevent it. There's just no active job running in the current version that would do it.

As for storage efficiency, this is something I'm going to investigate at "near" future (hopefully this summer) - but no promises here for schedule.

@ekuric This is still normal, the "load" will increase until the TTL is reached and older data is purged. By default it's something like 7 days.

**Comment by jeremyeder** [comment]
Hey guys,

With the default retention period of 7 days, metrics requires 22.69MB/pod/wk right now.
We're targeting support for 1000 nodes @ 125 pods for OpenShift 3.3.

125,000 * 22.69 = 2.84TB/wk for metrics, as the high watermark.

@burmanm would this rrd-style granularity-reduction-over-time be something you'd be able to commit to implementing for OpenShift 3.3?  I noticed it's been discussed http://www.datastax.com/dev/blog/metric-collection-and-storage-with-cassandra but that article is nearly 4 years old.

@mwringe has created a card to reduce the number of metrics collected.  I wonder what the final total per pod per week would be after this?  Reduction of a factor of 10 would bring us down to ~300GB for the high watermark which I think is reasonable to expect for a large cluster. 

Taken together, both of these features might even allow us to consider raising the default 7 day collection.  I am also concerned with the amount of data flying around the network.  At scale, even small efficiency improvements can move the needle.

@ekuric @timothysc

**Comment by mwringe** [comment]
@jeremyeder I suspect reducing the number of metrics collected (as described in that card) will reduce the amount collected by a lot more than just a factor of 10 (probably more like a factor of 100 or more) Right now we are essentially storing everything at the same resolution for the 7 days, when really the console needs a much smaller subset

**Comment by jeremyeder** [comment]
Ahh, good to know it's even better than I speculated.  So, who needs to be bribed to get this work prioritized for 3.3?

**Comment by mwringe** [comment]
@jeremyeder it would require adding in a bunch of features to Hawkular Metrics and I don't know when those can be accomplished

**Comment by jeremyeder** [comment]
OK -- who do we need to ping about that?

**Comment by mwringe** [comment]
@jeremyeder the Hawkular Metrics team. I have already requested this, but it looks like its not something simple to change with how Hawkular Metrics work

@jsanda and @stefannegrea can provide more information about their roll up work. But even with roll ups, it might not be at the fine grained level that would really allow us to slim down metrics to only what we need.

**Comment by timothysc** [comment]
Can we cross-link the issues?

**Comment by jsanda** [comment]
As @mwringe explained, data gets purged based on the METRIC_DURATION parameter. It defaults to 7 days. In part because of Cassandra being a distributed database, space is not immediately reclaimed when a delete happens. The data is replaced by what is called a tombstone. After a certain time, which is configurable, those tombstone will get purged when compaction runs. Cassandra's compaction job runs automatically, and there are no guarantees around when it will run. Given this, I would not necessarily expect to see a dramatic reduction in disk usage at 7 days. I would however expect the disk usage to start leveling off after 8 days.

In terms of reducing disk usage, there are a few things that we are working on that should help.

1) Don't use TTL for purging data [HWKMETRICS-191](https://issues.jboss.org/browse/HWKMETRICS-191)
Cassandra's TTL has an overhead of 4 bytes per cell/column. Handling data purge manually will get rid of that overhead.

2) Utilize rollups [HWKMETRICS-1](https://issues.jboss.org/browse/HWKMETRICS-1)
Matt and I have already been discussing this some. If we store data at lower resolutions with longer retentions, we can store less raw data and substantially reduce the storage overhead.

3) Move to Cassandra 3
The storage engine in Cassandra 3 has been rewritten and has less storage overhead. We need to do more testing to get a better idea of what kinds of reduction this will yield. This will happen eventually. We are doing upgrade testing with this now.

4) Use smaller data types
When possible, use smaller data types to reduce the overhead of each data point. Nothing is planned around this, but it has been discussed a little bit.

**Comment by jeremyeder** [comment]
@jsanda How much of this is realistic for OpenShift 3.3?

**Comment by mwringe** [comment]
@jeremyeder I don't know if I can talk about any specifics about upcoming releases, but I can say that these features are not yet completed in Hawkular Metrics, nor have we had a chance for the community to consume and provide feedback in origin.

**Comment by jeremyeder** [comment]
It sounds then like the current code in OpenShift 3.3 is what we will have for GA as far as metrics goes.

**Comment by rettori** [comment]
just so we have some benchmark, on a brief analysis, I asked Brian Brazil from prometheus to give us an idea on disk usage for a similar scenario and the answer is that for:
125k containers
20 metrics collected every 10 seconds
7 day window
basic math says it's (125000*(6*60*24*7)*20) - 151,200,000,000 samples.
According to him Brian), prometheus uses 1.3 bytes per sample, which means that for this scenario we would use: 196.56GB (196196,560,000,000 bytes) if the type 2 enconding is used.(https://prometheus.io/docs/operating/storage/#disk-usage)
This is around 9.3 KB per hour, per pod.

**Comment by mwringe** [comment]
@jeremyeder @rettori Do we have any 'acceptable' range of per pod usage that we should strive for? Something that would be deemed usable for our setup?

**Comment by jeremyeder** [comment]
Hard to say, but based on the above math...I believe we should strive for a more than 10x reduction, which could be achieved through the variety of methods discussed.  Dump what we don't use, compression as discussed on the jboss list, etc.

**Comment by jsanda** [comment]
Cassandra data files, i.e., SSTables are compressed by default. The compression algorithm used is configurable. LZ4 is the default. We have been doing some testing,and native Java GZIP provides much better compression. I ran a test in which I generated a 2.5 GB data set with the current set up that uses LZ4. The same test using GZIP shrinks the data set down to 768 MB. That is pretty significant. The gzip compression is not as fast as lz4, and I think the Cassandra docs mention that read performance is a little better with lz4. With that said, the disk space reduction may make it worth changing. And the compression can be altered at any time if we need to for whatever reason.

**Comment by jeremyeder** [comment]
Indeed!  And this seems low risk and attainable for the upcoming release, yes?  Also keep in mind it's not just the on-disk capacity, there's also memory usage and network traffic associated here as well.  And that's where trimming what we actually collect will improve efficiencies as well.  I'll assume that's for a later phase?

**Comment by jsanda** [comment]
Yes, we should be able to get this into the upcoming release. The change has to happen in the hawkular-metrics repo. I am going to create a ticket and submit a PR now for the compression change. 

Someone else will have to field the question about what we collect.

**Comment by jeremyeder** [comment]
Thanks -- can you let us know when we can get updated bits to test?
