### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by xelfe** [openshift/origin-metrics#165]
I use ansible installer and I own openshift 3.2. Metrics works well and after some times I got error 503 when I try to see the metrics. Into the logs I can see this error; GC overhead limit exceeded . Any way to fix that ?

**Comment by burmanm** [comment]
By increasing the memory limit might help. This error indicates that most of the time is spent on GC instead of doing actual work (probably because of high memory pressure). Any particular situation where this occurred? Can you repeat it?

**Comment by burmanm** [comment]
Do you have log lines of Cassandra just before the GC overhead limit exceeded (and perhaps the stacktrace also) ?

**Comment by jsanda** [comment]
I am going to close this issue since it has not had any recent activity. Please feel free to reopen if your issue is unresolved.
