### ISSUE TITLE
DNS issues; metric's self-signed certs don't have cluster_network IPs

### ISSUE THREAD

**Issue by juddmaltin-dell** [openshift/origin-metrics#168]
I'm seeing two types of errors in my heapster pod logs:

DNS lookup errors:

```
W0712 11:34:35.168016       1 node_aggregator.go:44] Failed to find node: node:flannel2-openshift-master-0.flannel9example.com
W0712 11:34:45.110316       1 node_aggregator.go:44] Failed to find node: node:flannel2-openshift-node-025hzih1.flannel9example.com
```

and Cert errors:

```
E0711 17:03:45.034823       1 kubelet.go:230] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "https://10.9.0.4:10250/stats/container/": Post https://10.9.0.4:10250/stats/container/: x509: certificate is valid for 172.30.0.1, 192.168.191.20, 192.168.9.5, not 10.9.0.4
```

10.9.0.4 - That's my cluster_network.  openshift-on-openstack has some extra networks.

```
[osp_admin@director ~]$ nova list  | grep 10.9.0.4
| d7874418-1b87-404b-bdbb-837eb57fb728 | flannel2-openshift-master-0.flannel9example.com      | ACTIVE  | -          | Running     | flannel2-cluster_network-bwpjwgoahijt=10.9.0.4; flannel2-fixed_network-fj36536xtyns=192.168.9.5, 192.168.191.20 |
[osp_admin@director ~]$
```

OpenShift is listening on 53:UDP  I also have a DNS server on a separate VM for access from outside.  /etc/resolv.conf on my OpenShift VMs point to that external DNS server.

Here's an AXFR from that DNS server:

```
[root@flannel2-infra ~]# dig @localhost flannel9example.com AXFR
;; Connection to ::1#53(::1) for flannel9example.com failed: connection refused.

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> @localhost flannel9example.com AXFR
; (2 servers found)
;; global options: +cmd
flannel9example.com.    86400   IN      SOA     flannel2-infra.flannel9example.com. openshift.flannel9example.com. 1467127738 43200 180 2419200 10800
flannel9example.com.    86400   IN      NS      flannel2-infra.flannel9example.com.
*.cloudapps.flannel9example.com. 86400 IN A     192.168.191.20
cloudforms.flannel9example.com. 86400 IN A      192.168.191.22
flannel2-infra.flannel9example.com. 86400 IN A  192.168.9.4
flannel2-lb.flannel9example.com. 86400 IN A     192.168.191.30
flannel2-openshift-master-0.flannel9example.com. 86400 IN A 192.168.9.5
flannel2-openshift-master-1.flannel9example.com. 86400 IN A 192.168.9.6
flannel2-openshift-node-025hzih1.flannel9example.com. 86400 IN A 192.168.9.10
flannel2-openshift-node-6033jc3s.flannel9example.com. 86400 IN A 192.168.9.9
flannel2-openshift-node-pgsis138.flannel9example.com. 86400 IN A 192.168.9.8
hawkular-metrics.flannel9example.com. 86400 IN A 192.168.191.30
overcloud.flannel9example.com. 86400 IN A       192.168.190.125
undercloud.flannel9example.com. 86400 IN A      192.168.120.61
flannel9example.com.    86400   IN      SOA     flannel2-infra.flannel9example.com. openshift.flannel9example.com. 1467127738 43200 180 2419200 10800
;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Jul 12 11:42:16 EDT 2016
;; XFR size: 15 records (messages 1, bytes 568)

```

Any hints?  Do I really have to gen my own certs?  Frowny.   If I change my /etc/resolv.conf to point to wherever OpenShift is listening 53:UDP, will that fail the system?

Bonus question:  Since the hawkular-metrics.example.com name is in the OpenShift DNS, where do I tell the openshift-infra VM's BIND to look for the address?  Should I just put the IP address of the router, and hope that it resolves correctly?

Can't this all be done with names?

Many thanks!
-judd

**Comment by mwringe** [comment]
This doesn't appear to be anything to do with the metric self signed certificates. Those certificates are only used for the Hawkular Metrics route and connections between Hawkular Metrics and Cassandra. 

The issues you are seeing are not because of the metrics install, because the node certificates are invalid:

> E0711 17:03:45.034823       1 kubelet.go:230] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "https://10.9.0.4:10250/stats/container/": Post https://10.9.0.4:10250/stats/container/: x509: certificate is valid for 172.30.0.1, 192.168.191.20, 192.168.9.5, not 10.9.0.4

Heapster gets the ip address of the node from the OpenShift master and then tries to connect to it. It then sees that the node is not valid for that ip address and throws an error.

The certificates should have been generated as part of the OpenShift install and should have the correct ip address in them, I would suspect that the nodes were not properly configured or installed.

We had this problem in the past (and had a section of the docs to cover how to fix it: https://docs.openshift.com/enterprise/3.1/install_config/upgrading/manual_upgrades.html#manual-updating-master-and-node-certificates). What version of OpenShift are you using and what version of origin-metrics?

**Comment by juddmaltin-dell** [comment]
Hi Matthew,

Thanks for the considered reply.

I'm using the https://github.com/redhat-openstack/openshift-on-openstack deploy of OSE 3.2 onto RHEL 7.2 OSP 8.

I've been able to deploy single-pod apps without issue on the cluster.  If I understand you correctly, and what your saying obtains, then I should fail to deploy multi-pod apps, and with similar errors.  No?  I'll try that and report back.

Where else might I find this error?

**Comment by mwringe** [comment]
> If I understand you correctly, and what your saying obtains, then I should fail to deploy multi-pod apps, and with similar errors.

No, it should only affect components which are directly trying to access the node. It should have no affect on multi pod apps or any other applications.

The metric components are a bit more complex than normal applications, and can outline issues that some users would not encounter otherwise.

**Comment by danielkucera** [comment]
I have the same probem: I changed node ip address, updated dns record but heapster is unable to connect to this new IP. My question is why heapster uses IP address to connect to node instead of hostname with is correctly included in certificate?
