### ISSUE TITLE
Data visualization

### ISSUE THREAD

**Issue by shilpapadgaonkar** [openshift/origin-metrics#17]
Hello,
For data visualization, I was looking at http://www.hawkular.org/docs/components/metrics/grafana_integration.html

However it mentions the use of influxDBv 0.8. 

I was earlier trying to use influxDB with heapster and had to face the problem with cpu metrics showing negative values due to a bug in influxDB v0.8.x
https://github.com/kubernetes/heapster/issues/640

Will this also impact data visualization for hawkular?

Regards,
Shilpa

**Comment by jcantrill** [comment]
@mwringe or @jimmidyson   have a comment?

**Comment by jimmidyson** [comment]
If the bug is due to infuxdb rather than heapster then no it won't affect hawkular.

**Comment by mwringe** [comment]
Please note that the influxDB compatibility layer in Hawkular Metrics only supports a subset of operations. While it is enough to graph simple charts, some more advanced options will not be available.

Data visualization is available directly in the OpenShift console. You just need to edit your `master-config.yaml` and change the `metricsPublicURL` to point to the Hawkular Metrics installation.

If you set you `HAWKULAR_METRICS_HOSTNAME` to `hawkular-metrics.example.com` in the template for the deployer, the `metricsPublicURL` will look like: 
`metricsPublicURL: "https://hawkular-metrics.example.com/hawkular/metrics"`

**Comment by mwringe** [comment]
Closing this issue as it targets an issue with an external project. Please reopen a similar issue if you encounter something similar with the components shipped with origin-metrics.
