### ISSUE TITLE
Changing heapster start arguments

### ISSUE THREAD

**Issue by shilpapadgaonkar** [openshift/origin-metrics#18]
Hello, 
I want to change heapster start arguments and hence I made a change in 
origin-metrics/deployer/templates/heapster.yaml on my machine and made it use auth insecure

"--source=kubernetes:${MASTER_URL}?auth=&insecure=true&useServiceAccount=true&kubeletPort=10255"

In my node-config.yaml I have 

kubeletArguments:
  "read-only-port":
    - "10255"

However when I checked the heapster logs, it still shows me the old arguments at start

Starting Heapster with the following arguments: --source=kubernetes:https://mastername:8443?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250 

Could you kindly suggest what I am missing here?

Thanks,
Shilpa

**Comment by mwringe** [comment]
Can you verify which deployer image you are using? And make sure that it matches the one that you built locally?

**Comment by shilpapadgaonkar** [comment]
I was earlier using the image hawkularqe/origin.
I then made the change for heapster, build the images locally as explained in the docu and then tried using

oc process -f ./metrics.yaml -v "HAWKULAR_METRICS_HOSTNAME=hawkular-smetrics.ops.example.com,MASTER_URL=https://master.example.com:8443,IMAGE_PREFIX=openshift/origin-,IMAGE_VERSION=devel,USE_PERSISTENT_STORAGE=false" -n smetrics | oc create -n smetrics -f -

The deployer pod fails with the following error message
 image pull failed for docker.io/openshift/origin-metrics-deployer:devel, this may be because there are no credentials on this request.

**Comment by mwringe** [comment]
What image prefix and version are you using when building your own images? Those need to match exactly the values you specify when deploying the template.

eg:
./build-images.sh --prefix=foo --version=bar
oc process -f metrics.yaml -v \
HAWKULAR_METRICS_HOSTNAME=hawkular-metrics.example.com,IMAGE_PREFIX=foo,IMAGE_VERSION=bar,USE_PERSISTENT_STORAGE=false \
| oc create -f -

**Comment by shilpapadgaonkar** [comment]
I had to include the registry IP and port along with the image prefix to solve the problem.

Now heapster starts with the arguments I had changed
Starting Heapster with the following arguments: --source=kubernetes:https://vmap                                                                                        gmstapp2n1.appa5.tsi-af.de:8443?auth=&insecure=true&useServiceAccount=true&kubel                                                                                        etPort=10255 --sink=

And now I am able to get metrics in heapster.
