### ISSUE TITLE
Enable commit log compression

### ISSUE THREAD

**Issue by jsanda** [openshift/origin-metrics#185]
Commit log compression was introduced in Cassandra 2.2. The compression can improve performance, and it also reduces disk usage. You can read more about it [here](http://www.datastax.com/dev/blog/updates-to-cassandras-commit-log-in-2-2). It is disabled by default. It is controlled by the `commitlog_compression` property in cassandra.yaml. We need to add the following:

```
commitlog_compression:
    - class_name: LZ4Compressor
```

**Comment by lucky-sideburn** [comment]
Hi,

I would like o add commitlog_compression but I did not find any config maps. How can I set this configuration parameter for hawkular-metrics pod?

Thank you in advance,
Eug
