### ISSUE TITLE
add support for dynamic PersistantVolume and PersistantVolumeClaim provisioning for cassandra deployer 

### ISSUE THREAD

**Issue by ekuric** [openshift/origin-metrics#189]
When it comes to scaling metrics pods ( particularly cassandra pods as part of metrics installation ) we can specify to use persistent storage 
``` 
USE_PERSISTENT_STORAGE=true 
``` 
For this to work, at time it is necessary to create PV in advance and make it available before metrics is started / tried to configure. 

If metric supported dynamic PVC provisioning then it will automatically get volume from storage provider and it will not be necessary to do this in advance what would make metrics starting and metrics  (auto) scaling easier. 

Example of dynamic PVC provisioning for EBS storage case : https://docs.openshift.com/enterprise/3.1/install_config/persistent_storage/dynamically_provisioning_pvs.html

**Comment by sdodson** [comment]
#138 does this but needs to be rebased

**Comment by ekuric** [comment]
thanks @sdodson who/when can rebase it?

**Comment by mwringe** [comment]
I have rebased detiber branch and submitted it as a new PR to be merged: https://github.com/openshift/origin-metrics/pull/192

**Comment by mwringe** [comment]
Its been merged, closing this issue.
