### ISSUE TITLE
Check for metrics image presence on nodes before trying to pull / download images prior openshift metrics start 

### ISSUE THREAD

**Issue by ekuric** [openshift/origin-metrics#195]
Add option to start metrics with using preloaded images on openshift nodes as (first) option when starting openshift metrics. 

openshift metrics will try to download metrics images and will fail to start if they cannot be downloaded - this will happen even if metrics images are present on node where metrics pods are scheduled to start. Currently it does not check for presence of metrics images and tries directly to download metrics images.

**Comment by bbguimaraes** [comment]
@ekuric: the pod definitions use the [default][default_pull_policy] image pull
policy:

> If a container’s `imagePullPolicy` parameter is not specified, OpenShift
> Origin sets it based on the image’s tag:
>
> 1. If the tag is `latest`, OpenShift Origin defaults `imagePullPolicy` to
> `Always`.
>
> 2. Otherwise, OpenShift Origin defaults `imagePullPolicy` to `IfNotPresent`.

The deployer template has some [options][deployer_options] to control the name
and version of the images used.

[default_pull_policy]: https://docs.openshift.org/latest/dev_guide/managing_images.html#image-pull-policy
[deployer_options]: https://github.com/openshift/origin-metrics/blob/master/docs/deployer_configuration.adoc#deployer-template-parameters

**Comment by ekuric** [comment]
@bbguimaraes yes, thank you, I think that it should check if image is present on node ( even tagged with  "latest" ) - what was the case in this test and proceed with configuration. Now it ignores it and fails  - even having exact image it needed to start. 

Adding in metrics.yml 
``` 
imagePullPolicy: IfNotPresent
``` 
helps, or getting some other tag for these images and use "IMAGE_VERSION" when starting metrics

**Comment by mwringe** [comment]
We are not going to change our imagePullPolicy to something like IfNotPresent, this breaks being able to pull in the latest images.

`I think that it should check if image is present on node ( even tagged with "latest" ) - what was the case in this test and proceed with configuration. Now it ignores it and fails - even having exact image it needed to start.`

Please open an issue with OpenShift to see if they can fix this on their end.

**Comment by timothysc** [comment]
We need to support air-gapped installations where the images are pre-pulled.

**Comment by timothysc** [comment]
@ekuric please BZ this item.
