### ISSUE TITLE
Run nodetool cleanup after deploying additional Cassandra nodes

### ISSUE THREAD

**Issue by jsanda** [openshift/origin-metrics#201]
Each Cassandra node is a assigned a set of keys (also referred to as tokens). When a new node joins the cluster, token assignments are recalculated so that the new node can take ownership of parts of the token ring. Nodes that currently own those tokens will stream data to the new node. Cassandra does not automatically delete the tokens after it finishes streaming. 

If you have a single node with 500 GB of data and deploy a second node without changing the replication_factor, the expectation is that each node should have roughly about 250 MB of data. After joining the cluster `nodetool status` should report about 50% load for the new node, but the load for the first node will be about the same. `nodetool cleanup` needs to be run on all existing cluster nodes to purge keys/token that are now owned by the new node. Clean up does not have to run immediately after the new node joins the cluster. It can run any time like during a regularly scheduled maintenance window.

Ultimately I think this maintenance should be handled by Hawkular Metrics for a couple reasons. First, we will need to perform this same maintenance in outside of OpenShift in other environments where Hawkular Metrics is used. Secondly, it reduces the operational complexity for OpenShift admins/users. I will create a high priority ticket in Hawkular Metrics for this if we want to handle it this way.

**Comment by mwringe** [comment]
Should this not be done at the Cassandra level instead of Hawkular Metrics handling this? It feels strange to have the Hawkular Metrics managing when a command is to be called on the Cassandra cluster. 

It also seems strange that Cassandra cannot automatically do something like this.

**Comment by jsanda** [comment]
> Should this not be done at the Cassandra level instead of Hawkular Metrics handling this?

What exactly do you mean? The commands are done over JMX. The maintenance could be carried out by a management agent co-located with Cassandra in the same machine/container or remotely. For a lot of management operations having some coordination is easier and often necessary. This is definitely one such case.

> It also seems strange that Cassandra cannot automatically do something like this.

Yes and no. `cleanup` can be somewhat heavyweight and take some time as it involves running compactions. Not doing it automatically gives you control over when exactly it runs. Having Cassandra do it automatically simplifies management but adds more overhead for running Cassandra which could potentially degrade performance. And the main selling points of Cassandra are definitely performance and scalability.

**Comment by jcantrill** [comment]
Might this be an opportunity to take advantage of openshift scheduled jobs?

**Comment by jsanda** [comment]
I am not (yet) familiar with openshift scheduled jobs. I just looked at [this article](https://blog.openshift.com/openshift-jobs/) and it certainly does seem applicable. Hawkular Metrics, as well as other Hawkular services, will be deployed in non-openshift environments; so, this is management functionality we are going to need in Hawkular one way or another. With that said, I am certainly open to  an alternative approach if it makes more sense for OpenShift deployments.
