### ISSUE TITLE
Enable UseCompressedOops JVM flag for Cassandra

### ISSUE THREAD

**Issue by jsanda** [openshift/origin-metrics#210]
Java object references are 8 bytes in size. For smaller heaps, like the sizes we use for Cassandra, object references can be reduced down to 4 bytes with the `UseCompressedOops` flag. This is a nice and easy heap memory utilization that we can apply.

**Comment by mwringe** [comment]
@jsanda and what happens if we are using larger heaps? Does this still apply? or is there only a certain limit where we should be using this value and have it disabled for others?

**Comment by jsanda** [comment]
Looks like it works with heaps up to 32 GB according to [this doc](https://docs.oracle.com/javase/8/docs/technotes/guides/vm/performance-enhancements-7.html#compressedOop). And for larger heaps, I believe the JVM will revert back to using 8 bytes. With Cassandra the recommended max heap size is 8 GB so this could be worthwhile.

**Comment by mwringe** [comment]
The Cassandra recommendations is not increase the heap beyond 8GB, so we should be good here to set this.
