### ISSUE TITLE
Cassandra Replication factor

### ISSUE THREAD

**Issue by spinolacastro** [openshift/origin-metrics#213]
I've recently faced a crash on a two pods cassandra cluster. Turn's out that i didn't realized hawkular creates a keyspace with 'replication_factor = 1', so hawkular was unable to write metric data until i put the node back.
If somebody is scaling for resilience instead performance will be frustrated.

I'd like suggest adding some scaling notes at cassandra docs to make it clear, i solved my issue with the following:

$ oc rsh <cassandra_pod>
$ csql --ssl 
csql> ALTER KEYSPACE hawkular_metrics WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '2'}  AND durable_writes = true;
csql> exit
$ nodetool repair

Now a node crash doesn't brake metric system.

**Comment by jsanda** [comment]
We are working on adding support to manage this upstream in hawkular-metrics. It is being tracked under https://issues.jboss.org/browse/HWKMETRICS-547. Any feedback is welcomed and appreciated!

**Comment by lpsantil** [comment]
Datastax [[0]](https://docs.datastax.com/en/cql/3.3/cql/cql_using/useUpdateKeyspaceRF.html) recommends running `nodetool repair -full` on each affected node (the cluster probably).

[0] https://docs.datastax.com/en/cql/3.3/cql/cql_using/useUpdateKeyspaceRF.html

**Comment by lpsantil** [comment]
Could this be another way of achieving the same thing?
```
oc exec <cassandra_pod> csql -e "'ALTER KEYSPACE hawkular_metrics WITH replication = {\'class\': \'SimpleStrategy\', \'replication_factor\': \'2\'} AND durable_writes = true;'"
```

**Comment by jsanda** [comment]
I am going to close this issue since it has not had any recent activity. Please feel free to reopen if your issue is unresolved.
