### ISSUE TITLE
Issue creating cassandra replication controller.

### ISSUE THREAD

**Issue by psteyn** [openshift/origin-metrics#215]
Hi,

When following the full-metrics install as per readme, using non-persistent storage, it fails to start up the replication controller for Cassandra with:

The ReplicationController "hawkular-cassandra-1" is invalid.
* spec.template.spec.containers[0].env[2].valueFrom: Invalid value: "": may not have more than one field specified at a time
* spec.template.spec.containers[0].env[3].valueFrom: Invalid value: "": may not have more than one field specified at a time

I've managed to do a workaround by removing:

                                  {   
                                        "name": "MEMORY_LIMIT",
                                        "valueFrom": {
                                            "resourceFieldRef": {
                                                "resource": "limits.memory"
                                            }
                                        }
                                    },
                                    {   
                                        "name": "CPU_LIMIT",
                                        "valueFrom": {
                                            "resourceFieldRef": {
                                                "divisor": "1m",
                                                "resource": "limits.cpu"
                                            }
                                        }
                                    }

Edit:  I'm not sure how good that workaround was, as the initial deployment config could have wanted to do more things after failing at valueFrom.

From the configuration so that there is only one 'valueFrom:' inside the env group, but something tells me this is a bug.

[root@master1 metrics]# oc version
oc v1.2.0
kubernetes v1.2.0-36-g4a3f9c5

**Comment by jperville** [comment]
Hi @psteyn , I just stumbled upon same issue and had to use the same workaround.

It seems that referencing limits.cpu and limits.memory in the manifests using downward API only works for openshift 1.3.0 and up; this is why it breaks for us who are using openshift 1.2.x.

**Comment by mwringe** [comment]
I believe the ansible install should have been setting the version of the components to be used. Did you use ansible to install OpenShift Origin? Or did you install it more manually?

The latest images for Origin Metrics are meant for the latest version of Origin. If you are using an older version, you will need to set the IMAGE_VERSION template parameter to the version you are running. See https://hub.docker.com/r/openshift/origin-metrics-deployer/tags/ for the list of available tags.

**Comment by psteyn** [comment]
Thank you. Makes sense.
I've used Ansible to install OpenShift Origin, correct.

I've reverted to using IMAGE_VERSION=v1.2.0.

**Comment by mwringe** [comment]
If Ansible did not properly set this IMAGE_VERSION, then we need to get that fixed.

**Comment by jperville** [comment]
Hi @psteyn I just figured out about the IMAGE_VERSION parameter. I will set it to v1.2.1 and see if it improves. For information, I am deploying openshift using a wrapper chef cookbook of mine over the https://github.com/IshentRas/cookbook-openshift3 cookbook.

**Comment by psteyn** [comment]
I used Ansible to install my 3 node cluster.
But I then did a git checkout of origin-metrics, and followed the README on the page.

Should I rather have used Ansible to also install metrics?
@Mwringe should Ansible have set an ENV var for me on my nodes?

**Comment by psteyn** [comment]
But yes, this issue may be closed as the solution is to use IMAGE_VERSION if your origin cluster is not already latest.
