### ISSUE TITLE
Use Config Maps for the Deployer

### ISSUE THREAD

**Issue by mwringe** [openshift/origin-metrics#217]
Its getting a bit crazy with the number of template parameters we have with the deployer and with users redeploying things, it means have to keep track of what the old deployment options were.

We should move over to config maps so that we can better handle the deployment options.

A couple of thoughts:

1) have one config map for all of the metric components. Each entry would start with something like cassandra.size or heapster.resolution, etc to represent which component it's being applied against.

2) have each component use the same config map. eg deployer, hawkular metrics, heapster, cassandra each use the same config map. This is so we can edit just one config map instead of potentially having to edit 4 different ones (or running into the issue where there is a main config map, and separate ones for each component that are not meant to be edited, but end up being manually edited anyways)

3) if values are passed as deployment parameters, then these should update the config map. We should mention in the description that these parameters are deprecated and to use the config map instead. We still want to make these backwards compatibility work with old commands. Any new options should not be allowed to be added as template parameters, only as config maps (unless it doesn't make sense to have them persisted between deployments, eg MODE)

4) since the deployer has edit permissions and can manually check if a secret or configmap is available, we should not force one to exist before hand. Eg so we don't need the empty secret thing we have right now. If no config map exists, then add the default one.

5) since people may want to config the config map before hand, they should be able to get the config map before the deployment. We should have an (optional) deployer mode to handle just creating the config map.

6) deployer options (eg mode, skip preflight, continue on error, etc) should not be in the config map, these should still be specified by template parameters. Eg anything which may not make sense to be reused between deployments shouldn't go in a config map.

7) anything which should be a secret (eg certificates, etc) should still be kept in a secret. We may want to move heapster_allowed_users to the config map though.

8) if the config map is missing a parameter, we should update the config map with the default value for this parameter. This will help us to add in new parameters in the future without having to regenerate the completely new config map.

**Comment by sdodson** [comment]
As someone automating installation of both metrics and logging it will be great when this is realized. CC'ing @sosiouxme as it'd also be great if the look and feel of the config maps between the two components can be as similar as possible.

**Comment by sosiouxme** [comment]
Logging already accepts a configmap / secret for its parameters in 3.3. See
origin docs:
https://docs.openshift.org/latest/install_config/aggregate_logging.html#aggregate-logging-specifying-deployer-parameters

**Comment by sdodson** [comment]
Right, I meant really just to connect the two projects here in hopes of sharing experiences.

**Comment by bbguimaraes** [comment]
@mwringe

> 4) [...] we don't need the empty secret thing we have right now.

The problem is there is a volume mount of the secret in the deployer pod
spec (because it can be populated pre-deployment).  We won't be able to
create the deployer pod if this secret doesn't exist.

> 5) [...] We should have an (optional) deployer mode to handle just
> creating the config map.

So the steps here (just to make sure I understand it) would be: run the
deployer once just to create the configmap with default or
deployer-generated values, change some values on the configmap, then run
the deployer again to do the deployment?

> 6) deployer options (eg mode, skip preflight, continue on error, etc)
> should not be in the config map

Do you see value in storing the image prefix and version on the
configmap?  I ask because it'd be tricky to do that, as the value is
used not only for each component, but also in the deployer pod spec.

> 8) if the config map is missing a parameter, we should update the
> config map with the default value for this parameter. This will help
> us to add in new parameters in the future without having to regenerate
> the completely new config map.

Wouldn't it be simpler for the deployer to just assume default values
for the configmap?  I don't see the benefit of updating the configmap.

**Comment by mwringe** [comment]
@bbguimaraes 

> The problem is there is a volume mount of the secret in the deployer pod
spec (because it can be populated pre-deployment).  We won't be able to
create the deployer pod if this secret doesn't exist.

You can get around this. You remove the dependency on the secret from the deployer template and the deployer reads the secret directly from the oc command. If the secret exists before running the deployer, then the deployer will read it directly and use it. Otherwise it will use the default.

I was playing around with this a bit before, I have a hacky, potentially no longer functioning initial start here: https://github.com/mwringe/origin-metrics/commit/01c49cecdc030008f3d2d1bb79ea21095462b033

> So the steps here (just to make sure I understand it) would be: run the
deployer once just to create the configmap with default or
deployer-generated values, change some values on the configmap, then run
the deployer again to do the deployment?

Yes, this would function similar to how OpenShift works. If you want to manage your own configuration files, you would first create them (openshift start --write-config=openshift.local.config), edit the files and then you would start openshift. If you didn't want to use your own configuration files and just want the default, you would just start openshift directly.

> Do you see value in storing the image prefix and version on the
configmap?  I ask because it'd be tricky to do that, as the value is
used not only for each component, but also in the deployer pod spec.

We probably do, but as you mentioned this might be a bit tricky. We may need to think about how to handle this nicely. For the initial version of this, we can leave out the image prefix and version.

Technically we could have a deployer wrapper that reads the prefix and version and then starts up the real, versioned deployer. But I really don't want to go down this route :)

> Wouldn't it be simpler for the deployer to just assume default values
for the configmap?  I don't see the benefit of updating the configmap.

Hmm, I was going under the assumption have having all the config options in a config map would work out better for users. They could just look at the config map, see what could be modified and make changes to it. I find the people tend to not always look at the documentation and are more likely to just look at the configuration and start making changes.

But, it may work out better to only use the config map to overwrite default values. This would also allow us to know the difference between say a value that a user has explicitly set versus a value which is just the default. ie say in version X we default a value to 10 while in version Y we want the new default to be 20, but if a user set the value to 5 we may want to use what they have set.

What are your thoughts on this? I kindof like it when configuration files contain everything so that I can easily see everything I can set and what the default values are. But this might not be the opinion of everyone.

**Comment by jcantrill** [comment]
I like the idea of seeing the available options as comments like a number of java config files.  You know what the default is and you can modify it if necessary, but I would imagine configmaps dont support comments.

**Comment by mwringe** [comment]
@jcantrill they don't, at least not as key value pairs. You could add in a property file to the config map, but this makes modifications a lot more difficult.

**Comment by bbguimaraes** [comment]
@mwringe: I'd prefer if the configmap had only the necessary information
(i.e. values that are different from the defaults).  Even more so if we
provide the option to generate a configmap that can then be edited.

**Comment by jcantrill** [comment]
@mwringe @bbguimaraes  what about as a compromise we have a section of the configmap which is the values used by the deployer and a separate section which is the defaults.  This would be the best of both worlds even though you end up with a bunch of unused content.  We also would need to document  what we are doing and if there were anyway to 'comment' the default section, that would be ideal

**Comment by mwringe** [comment]
> I'd prefer if the configmap had only the necessary information
(i.e. values that are different from the defaults).  Even more so if we
provide the option to generate a configmap that can then be edited.

Well, in this case, you wouldn't need an option to generate a configmap since if it's using default if nothing is specified, then the default configmap is an empty one :)

> what about as a compromise we have a section of the configmap which is the values used by the deployer and a separate section which is the defaults.

I am not sure I really like this idea. It means we would have something like "default.hawkularmetrics.metricsduration" and also "hawkularmetrics.metricsduration" in the same configmap and I don't trust users not to just edit the default.hawkularmetrics.metricsduration values instead of creating a new value without the "default."

But, I think I am an idiot and playing around with this a bit more I think that property files should work out nicely. If we load these as property files then we can comment out the defaults and have comments.

Eg:
```
oc get configmap myconfig -o yaml
apiVersion: v1
data:
  cassandra: |
    # use_persistent_storage: set to true for persistent storage, set to false to use non persistent storage
    # use_persistent_storage = false
    # cassandra_nodes: The number of Cassandra Nodes to deploy for the initial cluster
    # cassandra_nodes = 1
  hawkularmetrics: |
    # metrics_duration specified how many days to store metrics for
    # metrics_duration = 7
    # if users should be able to write metrics for their projects or not
    # user_write_access = false
kind: ConfigMap
metadata:
  creationTimestamp: 2016-09-14T13:47:39Z
  name: myconfig
  namespace: default
  resourceVersion: "274234"
  selfLink: /api/v1/namespaces/default/configmaps/myconfig
  uid: cd20197b-7a81-11e6-ab5a-c85b76045a27

```
