### ISSUE TITLE
Filter Metrics at the cAdvisor level

### ISSUE THREAD

**Issue by mwringe** [openshift/origin-metrics#218]
cAdvisor returns metrics for a lot of the running processes on the system its running on. This results in a lot of extra metrics that cAdvisor exposes, and for the most these are metrics we do not care about.

Currently we filter these metrics in Hawkular Metrics sink in Heapster. While this means that we are able to cut down in the number of metrics that get stored, it still means that Heapster is still downloading all the available metrics from the cAdvisor endpoint, and having to process all these metrics before sending them off to Hawkular Metrics.

If we could add metric filtering support to cAdvisor, we would be able to cut down on the size of files being sent to Heapster, which will decrease how long it takes for Heapster to download and process these files.

**Comment by wdp-007** [comment]
Is there any update for this issue? Is there any way to filter metrics on cadvisor?
