### ISSUE TITLE
Accessing A Specific Metric results in error.

### ISSUE THREAD

**Issue by cameron-scrace** [openshift/origin-metrics#221]
I'm following the documentation here: https://github.com/openshift/origin-metrics/blob/master/docs/hawkular_metrics.adoc and I have version 0.8.2.Final-redhat-1.

I can list all metrics and all cpu metrics for a pod, but trying to access a specific metric always gives an error.

`curl -k -H "Authorization: Bearer XXXXXXXXXXXXXXXX" -H "Hawkular-Tenant: openshift-infra" -X GET https://metrics.example.com/hawkular/metrics/metrics?tags=descriptor_name:cpu/usage,pod_name:hawkular-cassandra-1-np6ya  | python -m json.tool` 

The above command results in a json response with two metrics listed. But trying to access either of them fails.

`curl -k -H "Authorization: Bearer XXXXXXXXXXXXXXXX" -H "Hawkular-Tenant: openshift-infra" -X GET https://metrics.example.com/hawkular/metrics/counters/hawkular-cassandra-1/a3044b4a-7ad8-11e6-8dda-525400b064be/cpu/usage  | python -m json.tool`

> {
>     "errorMsg": "RESTEASY001185: Could not find resource for relative : /counters/hawkular-cassandra-1/a3044b4a-7ad8-11e6-8dda-525400b064be/cpu/usage of full path: https://metrics.example.com/hawkular/metrics/counters/hawkular-cassandra-1/a3044b4a-7ad8-11e6-8dda-525400b064be/cpu/usage"
> }

**Comment by mwringe** [comment]
I think you may have missed the step of URL encoding the metric id.

If the metric id is "hawkular-cassandra-1/a3044b4a-7ad8-11e6-8dda-525400b064be/cpu/usage" then if you want to use it in a URL it needs to be encoded. Which is "hawkular-cassandra-1%2Fa3044b4a-7ad8-11e6-8dda-525400b064be%2Fcpu%2Fusage"

**Comment by cameron-scrace** [comment]
Oops, I forgot to add that I tried that and got a different error.

```
curl -k -H "Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXX" -H "Hawkular-Tenant: openshift-infra" -X GET https://metrics.example.com/hawkular/metrics/counters/hawkular-cassandra-1%2Fa3044b4a-7ad8-11e6-8dda-525400b064be%2Fcpu%2Fusage
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /hawkular/metrics/counters/hawkular-cassandra-1/a3044b4a-7ad8-11e6-8dda-525400b064be/cpu/usage was not found on this server.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at metrics.example.com Port 443</address>
</body></html>
```
Also when I try to access metrics in the openshift web console I get 404s as well.

```
> https://metrics.example.com/hawkular/metrics/counters/hawkular-cass…8-11e6-8dda-525400b064be%2Fcpu%2Fusage/data?buckets=61&start=1473973165165 Failed to load resource: the server responded with a status of 404 (Not Found)
> hawkular-cassandra-1-np6ya:1 XMLHttpRequest cannot load https://metrics.example.com/hawkular/metrics/counters/hawkular-cass…8-11e6-8dda-525400b064be%2Fcpu%2Fusage/data?buckets=61&start=1473973165165. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://openshift.example.com:8443' is therefore not allowed access. The response had HTTP status code 404.
> https://metrics.example.com/hawkular/metrics/gauges/hawkular-cassan…1e6-8dda-525400b064be%2Fmemory%2Fusage/data?buckets=61&start=1473973165165 Failed to load resource: the server responded with a status of 404 (Not Found)
> hawkular-cassandra-1-np6ya:1 XMLHttpRequest cannot load https://metrics.example.com/hawkular/metrics/gauges/hawkular-cassan…1e6-8dda-525400b064be%2Fmemory%2Fusage/data?buckets=61&start=1473973165165. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://openshift.example.com:8443' is therefore not allowed access. The response had HTTP status code 404.
```
Hawkular Status returns successfully:

```
curl -k https://metrics.example.com/hawkular/metrics/status
{"MetricsService":"STARTED","Implementation-Version":"0.8.2.Final-redhat-1","Built-From-Git-SHA1":"9eb775892235e05bb1a7828af33a572e4945416e"}
```
Also if I click the link under the error message 'Metrics are not available' it successfully loads the hawkular welcome page. So I think that means metricsPublicURL is configured correctly.

**Comment by mwringe** [comment]
Ok, it sounds like the metricsPublicURL is configured properly.

Can you check the Heapster logs to make sure that Heapster is actually able to read metrics from the system?

I just checked on my system and this worked for me.

Can you try running the following?:
```
curl -v -k -H "Authorization: Bearer `oc whoami -t`" -H "Hawkular-tenant: openshift-infra"  -X GET https://hawkular-metrics.example.com/hawkular/metrics/metrics?tags=descriptor_name:cpu/usage,container_name:hawkular-cassandra-1 | python -m json.tool | grep -i \"id\"
```

Then url encoded the metric id and run the following

```
curl -v -k -H "Authorization: Bearer `oc whoami -t`" -H "Hawkular-tenant: openshift-infra"  -X GET https://hawkular-metrics.example.com/hawkular/metrics/counters/${URL_ENCODED_METRIC_ID} | python -m json.tool
```

**Comment by cameron-scrace** [comment]
Not sure if Heapster is doing anything, after it starts up there are no more logs, 
http://pastebin.com/f452G4au

Second curl results in a 404.
http://pastebin.com/NFXe1wiV

**Comment by burmanm** [comment]
So are you really hitting the right server?

``< Server: Apache/2.4.7 (Ubuntu)``

That's not Hawkular-Metrics, nor a proxy of Openshift?

**Comment by cameron-scrace** [comment]
There is a proxy in front of everything and it turns out it was the problem. It wasn't handling the encoded slashes properly. Adding the following line to the appropriate virtual host fixed the problem.

AllowEncodedSlashes NoDecode

Now I get graphs but they are empty, progress at least.
