### ISSUE TITLE
Supporting JGroups Clustering for Hawkular Metrics

### ISSUE THREAD

**Issue by mwringe** [openshift/origin-metrics#234]
The alerting component of Hawkular Metrics uses jgroups and this is not functioning with the current setup we have.

The Kubernetes JGroups clustering module has been added to wildfly, and it can detect the other nodes in the cluster, but it is not properly clustering with them. We need to determine why this is the case.

**Comment by penli1** [comment]
@mwringe in current(Metrics 3.4), do we support scale hawkular-metrics? like 
oc sacle rc/hawkular-metrics replicas=2

**Comment by mwringe** [comment]
yes, are you encountering any problems with this?

This issue should have been resolved a while ago and it was only even not functioning in this manner for a short period of time.

**Comment by penli1** [comment]
thx, not any issue,  we don't have such a  test case for scale hwakular-metrics, I'll add test case on scale hawkular-metrics.
