### ISSUE TITLE
Deploying metrics with NFS storage and supplementary group

### ISSUE THREAD

**Issue by fgiloux** [openshift/origin-metrics#236]
It is possible to specify supplementalGroup in the deployer template. This is however only applied to the deployer pod so that it is needed to add the same supplementalGroup to the Cassandra deployment configuration post metrics installation to get it working. Would it be possible that the deployer adds it automatically to Cassandra's deployment configuration?

**Comment by jcantrill** [comment]
@bbguimaraes something to consider with the ansible work if we do not already have this for configuration.  I noticed we provide such a tweak for the logging stack.
