### ISSUE TITLE
Is there a change in hawkular api from ose version 3.1 to ose 3.3?

### ISSUE THREAD

**Issue by shilpapadgaonkar** [openshift/origin-metrics#255]
Hello,
Is there a change in hawkular api from openshift enterprise v3.1 to 3.3?

Is the below cpu usage url still valid?

 cpuUsage_url = 'https://' + hwk_service + '/hawkular/metrics/counters/data?tags=descriptor_name:cpu/usage,pod_name:' + pod_names[x] + '&buckets=1&start='+ str(start) + '&end=' + str(end)

Regards

**Comment by jcantrill** [comment]
@mwringe  we should document the versions of metrics and how they relate to an openshift release so we can explicitly point users to specific versions of hawkular documentation.

**Comment by shilpapadgaonkar** [comment]
@mwringe could you urgently point me to cpu and uptime usage api documentation valid for ose 3.3

**Comment by mwringe** [comment]
Hawkular Metrics in v3.3 is a newer version than v3.1, but it should be API backwards compatible.

Are you sure you are running the exact same command between v3.1 and v3.3?

The same command works for me:

`curl -v -k -H "Authorization: Bearer `oc whoami -t`" -H "Hawkular-tenant: openshift-infra"  -X GET https://hawkular-metrics.example.com/hawkular/metrics/u%2Fusage,pod_name:hawkular-metrics-hawkular-metrics-a01f9\&buckets=1\&start=-10mn&end=0mn`

[Note: start of `-10mn` means the start time is 10 minutes ago, and end of `0mn` means the end time is now, based on the server clock and not the local users clock]

**Comment by mwringe** [comment]
@jcantrill the version of Hawkular Metrics (including the git commit it is based off) is available under the status endpoint (eg https://hawkular-metrics.example.com/hawkular/metrics/status).

The version is also available as an environment variable in the docker image ($HAWKULAR_METRICS_VERSION). Unfortunately you cannot easily get the environment variables specified in docker images via the oc tools or the console. You can get the information via 'docker inspect' though.

We have had an issue open for this for a long time already to have it displayed in the console: https://github.com/openshift/origin/issues/7077

**Comment by mwringe** [comment]
Also, just a note in case its unclear, I just used the relative timestamps in my curl there because it is easy to do. You can of course still continue to use the older absolute timestamps.

**Comment by shilpapadgaonkar** [comment]
yes this works...
I found some changes in heapster api though...

-`/api/v1/model/namespaces/{namespace-name}/pods/` used to return cpu and mem along with pod names as well.

The image used in 3.3 only returns us pod names.

The only change mentioned in documentation was about network metrics being available.

It would be very helpful if you guys could include changes to the (heapster+ hawkular) api along with the ose release notes.
