### ISSUE TITLE
Add multiple sinks to heapster

### ISSUE THREAD

**Issue by jdnieto** [openshift/origin-metrics#265]
Based on this [request](https://access.redhat.com/solutions/2486141).
I want to be able to make heapster to push metrics in multiple sinks without creating a additional heapster pods.

**Comment by jdnieto** [comment]
I have made a PR [#266](https://github.com/openshift/origin-metrics/pull/266)

**Comment by jsanda** [comment]
I am going to close this issue since it has not had any recent activity. Please feel free to reopen if your issue is unresolved.
