### ISSUE TITLE
Add delay setting for metrics-deployer validate step

### ISSUE THREAD

**Issue by penli1** [openshift/origin-metrics#274]
In a situation the OpenShift Cluster network is not good, e.g. the OpenShift is using proxy(https://docs.openshift.com/enterprise/3.0/admin_guide/http_proxies.html)
It takes long to pull the images, especially for hawkular-metrics image which is about 1.8G, cause the metrics-deployer status become error[1], but wait a while the pods are running well[2] .
Can we add some delay setting on the validate.sh to avoid the 'Error' status.
https://github.com/openshift/origin-metrics/blob/master/deployer/scripts/validate.sh

[1] error info
======== ERROR =========
validate_deployment_artifacts: 
Pod hawkular-cassandra-1-l1tkk from ReplicationController hawkular-cassandra-1 is in a Pending state.
This is most often due to waiting for the container image to pull and should eventually resolve.
  * * * * 
Pod hawkular-metrics-9hveu from ReplicationController hawkular-metrics is in a Pending state.
This is most often due to waiting for the container image to pull and should eventually resolve.
  * * * * 
Pod heapster-0xu9m from ReplicationController heapster specified an image that cannot be pulled.
ERROR: This is most often due to the image name being wrong or the docker registry being unavailable.
Ensure that you used the correct IMAGE_PREFIX and IMAGE_VERSION with the deployment.
There was an event for this pod with the following message:
Failed to pull image "/openshift3/metrics-heapster:3.4.0": image pull failed for /openshift3/metrics-heapster:3.4.0, this may be because there are no credentials on this request.  details: (net/http: request canceled)
  * * * * 

[2]# oc get pod
NAME                         READY     STATUS    RESTARTS   AGE
hawkular-cassandra-1-l1tkk   1/1       Running   0          9m
hawkular-metrics-9hveu       1/1       Running   0          9m
heapster-0xu9m               1/1       Running   0          9m
metrics-deployer-o8kbe       0/1       Error     0          10m

**Comment by mwringe** [comment]
We are going to be moving away from the deployer soon to ansible (which should hopefully have a better experience).

@bbguimaraes @jcantrill Can we make a note of this and incorporate this behaviour with the ansible work?
