### ISSUE TITLE
Deploy eventer container with heapster standalone

### ISSUE THREAD

**Issue by jacksilv** [openshift/origin-metrics#283]
Heapster is capable of collecting Kubernetes events, but its _eventer_ component is not included in the heapster pod template, while the heapster template offered by Kubernetes includes it (https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/influxdb/heapster-controller.yaml#L53).
We could include it by default in the "Heapster standalone" template or, alternatively, provide an environment variable to enable it.
If you agree I am ready to submit a PR to implement this solution.

**Comment by mwringe** [comment]
Heapster is being deprecated, I don't know if there is much point to putting that in here at this point in time. Heapster will be removed at some point when the new metrics architecture of Kubernetes is completed.

**Comment by jacksilv** [comment]
Hi, thanks for the update, I wass not aware Heapster is being deprecated, do you have any pointer on the roadmap or any information on the proposed solution?

**Comment by mwringe** [comment]
The roadmap can be found here: https://docs.google.com/document/d/1z7R44MUz_5gRLwsVH0S9rOy8W5naM9XE5NrbeGIqO2k/edit#heading=h.zay55j55blvz

Essentially for the system metrics, those will be collected by an internal mechanism.

For the long term storage and graphing of metrics (and handling of custom metrics) those will be handed by Hawkular components (we have an agent right now which will collect custom pod metrics which will expanded to include the other metrics as well).

For events, I don't believe we have something concrete planned for that yet, but it is something we do need to consider. 

Could you let us know what your event storage requirements and usecases are?

**Comment by jacksilv** [comment]
We are using Influx to store other applicative metrics, so we want to store the events collected by _eventer_  to our influxDB instance, and show them with a dedicated Grafana Dashboard (https://github.com/kubernetes/heapster/blob/master/grafana/dashboards/influxdb_withfields/events.json).
Then we plan to use Grafana 4.0 alerting feature to fire alerts on events.
