### ISSUE TITLE
Make origin-metrics work on Kubernetes

### ISSUE THREAD

**Issue by metmajer** [openshift/origin-metrics#287]
Hi there, great project!

I was wondering whether origin-metrics would work on plain Kubernetes? From what I've seen, the Templates in the root should be transformed into Lists, but other than that? Has anyone tried this yet? I really like the completeness of this solution.

Cheers, Martin

**Comment by mwringe** [comment]
Yeah, its something we have been thinking about.

Its probably not a huge issue to get this up and running on a plain kubernetes setup. But its not necessarily trivial.

We would have to change how our components are being deployed, and figure out a different way to generate our secrets in a slightly different manner.

Currently we use OpenShift authentication to verify users, but that can be changed to user usernames and passwords instead.

The agent (https://github.com/hawkular/hawkular-openshift-agent) which is used to gather application metrics, should just work on Kubernetes.

We currently display metrics in the OpenShift console, but we also have grafana integration which would work if someone was using plain Kubernetes
