### ISSUE TITLE
Hawkular metrics not serving requests

### ISSUE THREAD

**Issue by roshan-mr** [openshift/origin-metrics#290]
Hi,

I have deployed the hawkular in my openshift cluster. I can see that the pods are running. But if I do a curl to the metrics endpoint, then I am not getting any response.

=====================
curl -k -H "Hawkular-Tenant: stag-au" -X GET https://hawkular-metrics.example.net/hawkular/metrics

      <h1>Application is not available</h1>
      <p>The application is currently not serving requests at this endpoint. It may not have been started or is still starting.</p>
  
======================
======================
curl -I -k --cacert cacert.pem  -H "Hawkular-Tenant: stag-au" -X GET https://hawkular-metrics.example.net/hawkular/metrics

HTTP/1.0 503 Service Unavailable
Pragma: no-cache
Cache-Control: private, max-age=0, no-cache, no-store
Connection: close
Content-Type: text/html
=========================

I am seeing the following in the pod logs

============
07:35:13,491 INFO  [org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] (metricsservice-lifecycle-thread) The keyspace hawkular_metrics is using a replication_factor of 1
07:35:13,790 INFO  [org.hawkular.metrics.core.service.MetricsServiceImpl] (metricsservice-lifecycle-thread) HAWKMETRICS100001: Using a key space of 'hawkular_metrics'
07:35:13,905 INFO  [org.hawkular.metrics.core.service.MetricsServiceImpl] (metricsservice-lifecycle-thread) HAWKMETRICS100008: Using max size of 2048 for string metrics
07:35:13,905 INFO  [org.hawkular.metrics.core.service.MetricsServiceImpl] (metricsservice-lifecycle-thread) HAWKMETRICS100009: Using max number of retries 5 and max retry delay of 30000 ms for inserting data points
07:35:13,909 INFO  [org.hawkular.metrics.core.service.MetricsServiceImpl] (metricsservice-lifecycle-thread) HAWKMETRICS100007: Using default data retention of 604800 seconds
07:35:13,916 INFO  [org.hawkular.metrics.core.dropwizard.MetricsInitializer] (metricsservice-lifecycle-thread) Creating metrics
07:35:14,107 INFO  [org.hawkular.metrics.core.dropwizard.MetricsInitializer] (RxComputationScheduler-4) Finished creating metrics in 190 ms
07:35:14,192 WARN  [com.datastax.driver.core.Cluster] (cluster2-worker-3) Re-preparing already prepared query is generally an anti-pattern and will likely affect performance. Consider preparing the statement only once. Query='SELECT DISTINCT tenant_id, tname FROM metrics_tags_idx'
07:35:14,268 INFO  [org.hawkular.metrics.core.util.GCGraceSecondsManager] (metricsservice-lifecycle-thread) Checking tables in hawkular_metrics to see if gc_grace_seconds needs to be updated
07:35:14,277 INFO  [org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] (metricsservice-lifecycle-thread) HAWKMETRICS200005: Metrics service started
07:35:14,280 INFO  [org.hawkular.metrics.core.util.GCGraceSecondsManager] (RxComputationScheduler-1) Finished gc_grace_seconds updates in 11 ms
==============================

What could be the issue?

Regards,
Roshan

**Comment by mwringe** [comment]
Please do not paste the logs directly into the issue, they don't always get displayed properly. If you attach it as a file (or just a gist and paste the link) that usually works out better.

Are you sure that Hawkular Metrics is not working properly? What is the state of the metric components? 
eg: `oc get pods -n openshift-infra`, are they all in the 1/1 state?
