### ISSUE TITLE
Hawkular documentation clarification

### ISSUE THREAD

**Issue by stuartbrierley1** [openshift/origin-metrics#307]
Hi,
I've been working with the hawkular API to extract metrics and the documentation does not make any sense to me. This section...

Calculating CPU Millicore Percentage
If you want to convert percent of cores used into a millicore used metric instead you just need to multiple the percentage by 1000:
millicore_percentage = core_percentage * 1000

Is the result in millicores or percentage? Surely percentage of millicores should be the same as the percentage of cores used?

**Comment by mwringe** [comment]
There is now a cpu rate metric being stored, so you can use that instead of calculating it yourself.

The wording is probably a bit confusing. It should probably just say:

millicores = core_percentage * 1000
