### ISSUE TITLE
Make it possible to capture Cassandra heap dumps

### ISSUE THREAD

**Issue by jsanda** [openshift/origin-metrics#317]
When Cassandra throws an OOME, it can generate a heap dump file that can be helpful for debugging. If the ```CASSANDRA_HEAPDUMP_DIR``` environment variable is set, then Cassandra will write the heap dump file to that directory. I would like to set this variable by default so that we do lose the heap dump when the pod restarts.

**Comment by jcantrill** [comment]
I think this is a great idea, but how to we manage this in a containerized env?  Do we make the assumption that every cassandra node has access to persistent storage that is separate from where it writes its data?

**Comment by jsanda** [comment]
I know we cannot assume persistent storage. **If** persistent storage is used, then the heap dumps should be stored there (ideally) so that they are not lost on restart.

**Comment by jcantrill** [comment]
Is the heap file something that can in addition to being written to a directory, dumped to the log so that we may possibly ingest it to ES and then consumed later?

**Comment by jsanda** [comment]
It's in a binary format, and I primarily use http://www.eclipse.org/mat/ for viewing and analyzing heap dumps. I am not sure that ES is the right tool. MAT generates different reports and allows you to drill down into different parts of the object graph to see what is consuming memory.

**Comment by mwringe** [comment]
@jsanda so we can fairly easily add this in, that shouldn't be a big problem. I am more concerned about the size of the heapdump and how that might affect someones storage. I am assuming in most cases this would be maybe a few gigs?

**Comment by jsanda** [comment]
Yes, the heap dump files can get rather large, so you do not want to leave them lying around.

**Comment by mwringe** [comment]
I am a bit concerned how this will affect users with limited disk space. So the OOME happens and we write the heap dump to disk. Cassandra restarts, but shortly after it runs out of space on disk and we run into more problems.

The heap dump is not really something predictable and users may not be calculating for its disk space.
