### ISSUE TITLE
Question: Querying the labels field for a single label.

### ISSUE THREAD

**Issue by ScottWe** [openshift/origin-metrics#321]
Hello,

I am trying to aggregate the metrics for all pods created under a specific deployment configuration. I've tried running my request with `tags=labels:.*deploymentconfig:mysql.*`, which does aggregate the data. However, if there was another deployment config named mysql-1, I would aggregate both. I know such name prefixing will occur in my environment. If I try `tags=labels:^(.*,)?deploymentconfig:mysql(.*,)?$`, I produce the error

```json
{"errorMsg":"Invalid tags: labels:^(.*,)?deploymentconfig:mysql(.*,)?$,descriptor_name:cpu/usage"}
```

Is a strict query for a single label supported in Hawkular?

**Comment by mwringe** [comment]
what about something like this:

tags=labels(?=.*\\deploymentconfig:mysql\\b).*$

**Comment by ScottWe** [comment]
Unfortunately "-" is also a boundary character so \b doesn't help. The same issue arises with \W. Your suggestion led me to find \x2C though, which matches a comma as an ASCII value (0x2C). This seems to work.

**Comment by jsanda** [comment]
I guess it fell off my radar, but I thought we agreed a while back that we would flatten the labels in Hawkular Metrics so that we can more easily use the tag query language. @mwringe do you recall the discussion?

**Comment by mwringe** [comment]
In OpenShift origin, we should have support for more flattened metrics, but its not in any OpenShift release yet.

The old labels="foo=bar,A=B" will still exist, but we will now also have "labels.foo=bar" and "labels.A=B"

**Comment by andrewklau** [comment]
@ScottWe could you let me know what your final query string was? I seem to be stuck with this now

**Comment by jsanda** [comment]
I am going to close this issue since it has not had any recent activity. Please feel free to reopen if your issue is unresolved.
