### ISSUE TITLE
Hawkular cannot find hawkular-jgroups.keystore

### ISSUE THREAD

**Issue by gustavohenrique** [openshift/origin-metrics#328]
Hi,
I can't deploy Hawkular into Openshift Origin. It seems the file hawkular-jgroups.keystore was not found.

`ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service jboss.jgroups.channel.ee: org.jboss.msc.service.StartException in service jboss.jgroups.channel.ee: java.security.PrivilegedActionException: java.io.FileNotFoundException: hawkular-jgroups.keystore (No such file or directory)`

My hawkular-rc.yml:

apiVersion: v1
kind: ReplicationController
metadata:
  name: hawkular-metrics
  labels:
    metrics-infra: hawkular-metrics
    name: hawkular-metrics
spec:
  selector:
    name: hawkular-metrics
  replicas: 1
  template:
    version: v1
    metadata:
      labels:
        metrics-infra: hawkular-metrics
        name: hawkular-metrics
    spec:
      serviceAccount: hawkular
      containers:
      - image: docker.io/openshift/origin-metrics-hawkular-metrics:v1.4.1
        name: hawkular-metrics
        ports:
        - name: http-endpoint
          containerPort: 8080
        - name: https-endpoint
          containerPort: 8443
        - name: ping
          containerPort: 8888
        command:
        - "/opt/hawkular/scripts/hawkular-metrics-wrapper.sh"
        - "-b"
        - 0.0.0.0
        - "-Dhawkular.metrics.cassandra.nodes=hawkular-cassandra"
        - "-Dhawkular.metrics.cassandra.use-ssl"
        - "-Dhawkular.metrics.openshift.auth-methods=openshift-oauth,htpasswd"
        - "-Dhawkular.metrics.openshift.htpasswd-file=/secrets/hawkular-metrics.htpasswd.file"
        - "-Dhawkular.metrics.allowed-cors-access-control-allow-headers=authorization"
        - "-Dhawkular.metrics.default-ttl=7"
        - "-Dhawkular.metrics.admin-tenant=_hawkular_admin"
        - "-Dhawkular-alerts.cassandra-nodes=hawkular-cassandra"
        - "-Dhawkular-alerts.cassandra-use-ssl"
        - "-Dhawkular.alerts.openshift.auth-methods=openshift-oauth,htpasswd"
        - "-Dhawkular.alerts.openshift.htpasswd-file=/secrets/hawkular-metrics.htpasswd.file"
        - "-Dhawkular.alerts.allowed-cors-access-control-allow-headers=authorization"
        - "-Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true"
        - "-Dorg.apache.catalina.connector.CoyoteAdapter.ALLOW_BACKSLASH=true"
        - "-Dcom.datastax.driver.FORCE_NIO=true"  
        - "-DKUBERNETES_MASTER_URL=https://192.168.99.101:8443"
        - "-DUSER_WRITE_ACCESS=False"
        - "--hmw.keystore=/secrets/hawkular-metrics.keystore"
        - "--hmw.keystore_password_file=/secrets/hawkular-metrics.keystore.password"
        - "--hmw.truststore=/secrets/hawkular-metrics.truststore"
        - "--hmw.truststore_password_file=/secrets/hawkular-metrics.truststore.password"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MASTER_URL
          value: "https://192.168.99.101:8443"
        - name: JGROUPS_PASSWORD
          value: "<password>"
        - name: OPENSHIFT_KUBE_PING_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPENSHIFT_KUBE_PING_LABELS
          value: "metrics-infra=hawkular-metrics,name=hawkular-metrics"
        - name: STARTUP_TIMEOUT
          value: "500"
        volumeMounts:
        - name: hawkular-metrics-secrets
          mountPath: "/secrets"
        - name: hawkular-metrics-client-secrets
          mountPath: "/client-secrets"
        readinessProbe:
          exec:
            command:
            - "/opt/hawkular/scripts/hawkular-metrics-readiness.py"
        livenessProbe:
          exec:
            command:
            - "/opt/hawkular/scripts/hawkular-metrics-liveness.py"
      volumes:
      - name: hawkular-metrics-secrets
        secret:
          secretName: hawkular-metrics-secrets
      - name: hawkular-metrics-client-secrets
        secret:
          secretName: hawkular-metrics-account

**Comment by mwringe** [comment]
How are you installing metrics?

**Comment by gustavohenrique** [comment]
I'm installing manually. I analyzed the templates and scripts from origin-metrics and openshift-ansible repositories so I created my own YAML files to create secrets, services, routes, replication controllers, etc. At this moment the only thing I installed successfully was Cassandra.
I generated the certificates, keystores and truststores, according to the scripts from that repositories but I 'm not found any references to hawkular-jgroups.keystore file.

**Comment by mwringe** [comment]
I think the problem is that you are trying to use the latest openshift ansible code to deploy an older version of origin metrics. If you are using 1.4.1, then you need to checkout out that release of openshift ansible and use that.

**Comment by jpkrohling** [comment]
@gustavohenrique , can you confirm this works when using the latest master from both the Ansible repository and origin-metrics?

**Comment by gustavohenrique** [comment]
@jpkrohling Using from master it looks like works. Thanks!
