### ISSUE TITLE
Network and filesystem usage

### ISSUE THREAD

**Issue by shilpapadgaonkar** [openshift/origin-metrics#33]
Hello,
I do not see any filesystem usage or network metrics in hawkular which were available in heapster -
https://github.com/kubernetes/heapster/blob/master/docs/storage-schema.md

Do you plan to include this in hawkular?

Regards,
Shilpa

**Comment by shilpapadgaonkar** [comment]
For filesystem, I see this already open

https://issues.jboss.org/browse/HWKMETRICS-295

**Comment by mwringe** [comment]
We are currently receiving all the metrics available from Heapster. 

The metrics listed under that schema (https://github.com/kubernetes/heapster/blob/master/docs/storage-schema.md) is not a good indication of what metrics are actually available. Some of those metrics are only available at the node/system level and not at the container level.

Eg https://github.com/kubernetes/heapster/issues/368

We are not filtering or removing any container metrics in the Hawkular components. And unfortunately this is not something we can change ourselves. This requires changes to be done at the Kubernetes and cAdvisor level.

**Comment by mwringe** [comment]
I added a section to the docs explaining how to reach the system level filesystem data: https://github.com/openshift/origin-metrics/blob/master/docs/hawkular_metrics.adoc#accessing-node-metrics

Unfortunately we are still waiting for upstream kubernetes to expose these metrics at the container level.

**Comment by mwringe** [comment]
I am closing this issue. We now have per pod network usage, and per node filesystem usage.

If you wish for per pod filesystem usage, you will have to submit a feature request to Heapster.
