### ISSUE TITLE
Cassandra commitlogs keep accumulating and are never flushed

### ISSUE THREAD

**Issue by AlbertoPeon** [openshift/origin-metrics#330]
In our cluster metrics deployment, we have noticed that Cassandra fills up very quickly the persistenvolume in `/cassandra_data` with uprocessed commitlogs
```
$ oc exec hawkular-cassandra-1-bfh1k -- ls -l /cassandra_data/commitlog/ | head  
total 1207956
-rw-r--r--. 1 1000020000 1000020000 5123174 Apr  4 12:43 CommitLog-6-1491308793097.log
-rw-r--r--. 1 1000020000 1000020000 5129411 Apr  4 12:50 CommitLog-6-1491308793098.log
-rw-r--r--. 1 1000020000 1000020000 5092569 Apr  4 12:57 CommitLog-6-1491308793099.log
-rw-r--r--. 1 1000020000 1000020000 5138646 Apr  4 13:03 CommitLog-6-1491308793100.log
-rw-r--r--. 1 1000020000 1000020000 5117004 Apr  4 13:10 CommitLog-6-1491308793101.log
-rw-r--r--. 1 1000020000 1000020000 5111812 Apr  4 13:17 CommitLog-6-1491308793102.log
-rw-r--r--. 1 1000020000 1000020000 5140588 Apr  4 13:24 CommitLog-6-1491308793103.log
-rw-r--r--. 1 1000020000 1000020000 5097995 Apr  4 13:31 CommitLog-6-1491308793104.log
-rw-r--r--. 1 1000020000 1000020000 5091782 Apr  4 13:38 CommitLog-6-1491308793105.log
$ oc exec hawkular-cassandra-1-bfh1k -- ls -l /cassandra_data/commitlog/ | wc -l 
240
```
It seems that for some reason the commitlogs keep accumulating and are never flushed. The metrics work to the point where the PV is full and Cassandra crashes (the pod continues running but hawkular cannot connect anymore to it)

Our PVs are based on NFS but the same behaviour appears when using an `EmptyDir`.

What is the reason of this? Is there any way to avoid this problem?

Thanks!

**Comment by jcantrill** [comment]
@AlbertoPeon Can you provide additional information about the version of metrics you are deploying?  The version of OpenShift you are running?

**Comment by mwringe** [comment]
For you PV, what size are you setting it to be? How many pods are you running and how quickly are the commit logs filling the space?

**Comment by AlbertoPeon** [comment]
We are running Openshift Origin 1.4.1 and also version v1.4.1 of Cassandra, Hawkular an Heapster Images. 

The metrics were originally deployed using the procedure referenced in: https://docs.openshift.com/container-platform/3.3/install_config/cluster_metrics.html#deploying-the-metrics-components

For the size of the PVC, I tried with different sizes from 50Gi to 200Gi and `EmptyDir` and we are seeing the same behavior in all cases.

After three days of running with an empty volume, I see:
```
sh-4.2$ df -h /cassandra_data/                                       
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        80G   13G   68G  16% /cassandra_data
sh-4.2$ du -sh /cassandra_data/*
1.9G	/cassandra_data/commitlog
318M	/cassandra_data/data
```

The number of files in `/cassandra_data/commitlog` keep growing in the order of ~200 per day.

**Comment by jsanda** [comment]
The commit log directory size has an upper limit that defaults to the smaller of 8 GB or 1/4 the volume. When all of the mutations in a commit log file have been flushed to data files on disk, the commit log file will be deleted. If the upper limit is reached, Cassandra will force flush tables in memory so that it can delete commit log files.

**Comment by AlbertoPeon** [comment]
Hi @jsanda, I *think* the problem disappear with the upgrade to 1.5? We still have logs of files in the commitlogs but they are not filling up the PVC.
```
$ oc exec hawkular-cassandra-1-b9k5r -- ls -l /cassandra_data/commitlog/ | wc -l
1548
```
But I suspect files are being flushed and recycled as time passes (probably the expected behavior)

**Comment by jsanda** [comment]
Yes that is the expected behavior. We have had some other users report
problems with the commit log, and I do think it is related to the
compression.

If your problems are resolved would you mind closing the ticket?

Thanks

**Comment by AlbertoPeon** [comment]
Of course, thanks a lot for your help!
