### ISSUE TITLE
wrong wget URL in openshift metrics docs for hosa

### ISSUE THREAD

**Issue by jmazzitelli** [openshift/origin-metrics#333]
> https://docs.openshift.org/latest/install_config/cluster_metrics.html#deploying-hawkular-openshift-agent

Those OpenShift Metrics docs are incorrect - its pointing to the wrong github links to wget. It says:

```
$ wget https://github.com/openshift/origin-metrics/blob/master/hawkular-agent/hawkular-openshift-agent-configmap.yaml
$ wget https://github.com/openshift/origin-metrics/blob/master/hawkular-agent/hawkular-openshift-agent.yaml
```

But when you wget those, you are getting the actual HTML page for those files. We want to tell the user to get the raw files, whose links are:

```
https://raw.githubusercontent.com/openshift/origin-metrics/master/hawkular-agent/hawkular-openshift-agent-configmap.yaml
https://raw.githubusercontent.com/openshift/origin-metrics/master/hawkular-agent/hawkular-openshift-agent.yaml
```

**Comment by jsanda** [comment]
I am going to close this issue since it has not had any recent activity. Please feel free to reopen if your issue is unresolved.
