### ISSUE TITLE
documentation issue, "Accessing all metrics for a Project" part, the project name of output is not the same with the given project

### ISSUE THREAD

**Issue by juzhao** [openshift/origin-metrics#334]
"Accessing all metrics for a Project" part, 
If you wish to get a list of all metrics on available under the project **test** you can perform the following command, this means we are going to use project test, but from the command output  "tenantId": "openshift-infra",  we are use project openshift-infra, not project test

**Comment by jcantrill** [comment]
@juzhao Could you please submit a PR to correct the issue you are seeing against the document in question?

**Comment by mwringe** [comment]
The line in question is: https://github.com/openshift/origin-metrics/blame/master/docs/hawkular_metrics.adoc#L97

We would just need to change the 'openshift-infra' to 'test' here.

Doc PRs are always welcome :)

**Comment by juzhao** [comment]
@jcantrill @mwringe 
issue created
https://bugzilla.redhat.com/show_bug.cgi?id=1443272
