### ISSUE TITLE
heapster: Failed to list *v1.Pod: proto: Affinity: wiretype end group for non-group

### ISSUE THREAD

**Issue by hamelg** [openshift/origin-metrics#337]
We use the latest image openshift/origin-metrics-heapster and its graphite sink as standalone heapster. Each second, heapster emits this error :

E0420 09:20:04.500744       1 reflector.go:190] k8s.io/heapster/metrics/heapster.go:322: Failed to list *v1.Pod: proto: Affinity: wiretype end group for non-group

What does it mean ?
It seems it's harmless, the graphite sink works fine.
Thanks.

**Comment by mwringe** [comment]
@DirectXMan12 any idea?

**Comment by DirectXMan12** [comment]
Can you please indicate which version of OpenShift that you're testing this against?  What's the version of Heapster listed in the logs?

**Comment by hamelg** [comment]
# openshift version
openshift v3.3.1.14
kubernetes v1.3.0+52492b4
etcd 2.3.0+git
sh-4.2$ heapster --version
version: v1.3.0
commit: abbfe6e

**Comment by hamelg** [comment]
```
# openshift version
openshift v3.4.1.24
kubernetes v1.4.0+776c994
etcd 3.1.0-rc.0
```

After upgrading to openshift 3.4, these warnings have vanished.
