### ISSUE TITLE
Cannot use oc debug with Hawkular Metrics

### ISSUE THREAD

**Issue by mwringe** [openshift/origin-metrics#341]
We cannot use oc debug anymore with Hawkular Metrics due to the way the keystores and truststores are setup.

Steps to reproduce:
\# debug the Hawkular Metrics pod
oc debug ${HAWKULAR_METRICS_POD}
\# export the hostname, the default one is too long and will cause Hawkular Metrics to fail
export HOSTNAME=hawkular-metrics-debug
\# start hawkular metrics with its command

/opt/hawkular/scripts/hawkular-metrics-wrapper.sh -b 0.0.0.0 .....

\# notice that Hawkular Metrics starts up properly
\# stop Hawkular Metrics (ctrl-c) and rerun the above command.

notice the following failure:
Converting the PKCS12 keystore into a Java Keystore
keytool error: java.io.IOException: Keystore was tampered with, or password was incorrect
java.io.IOException: Keystore was tampered with, or password was incorrect
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:780)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at sun.security.tools.keytool.Main.doCommands(Main.java:799)
	at sun.security.tools.keytool.Main.run(Main.java:345)
	at sun.security.tools.keytool.Main.main(Main.java:338)
Caused by: java.security.UnrecoverableKeyException: Password verification failed
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:778)
	... 7 more

**Comment by mwringe** [comment]
@jpkrohling could you take a look at this at some point?

**Comment by mwringe** [comment]
@jpkrohling any update on this? This is also affecting Cassandra. We must ensure that we can use oc debug commands

**Comment by jpkrohling** [comment]
Sorry, this wasn't on my radar. I'm adding to my task list.

**Comment by jpkrohling** [comment]
The problem happens because the PKCS, Keystore and Trust store are generated on boot. Their passwords are generated also during the boot, in case they are not specified. So, on a second run, the script generates new passwords, but the files exist already and created with another password.

A workaround is to specify the passwords by exporting the following env vars:
```
export KEYSTORE_PASSWORD=the-keystore-password
export TRUSTSTORE_PASSWORD=the-truststore-password
```

A second workaround is to remove the three files:

```
rm -f \
  /opt/hawkular/auth/hawkular-metrics.keystore \
  /opt/hawkular/auth/hawkular-metrics.pkcs12 \
  /opt/hawkular/auth/hawkular-metrics.truststore
```

In any case, I'm preparing a PR that will automatically remove those files should they exist.
