### ISSUE TITLE
Cassandra pod cannot work due to log "CassandraDaemon.java:709 - Has no permission to create directory /cassandra_data/data"

### ISSUE THREAD

**Issue by lirenjiede** [openshift/origin-metrics#356]
I just use openshift-ansible1.5 to install openshift 1.5. But the metrics can not work.
**Env**
openshift-ansible：1.5
openshift：1.5.1
metric：1.5.1

`[root@bogon ~]# oc get pods`
`NAME                         READY     STATUS             RESTARTS   AGE`
`hawkular-cassandra-1-pftvq   0/1       CrashLoopBackOff   11         39m`
`hawkular-metrics-xrdxk       0/1       Running            6          39m`
`heapster-9wtwl               0/1       Running            4          39m`

`oc logs hawkular-cassandra-1-pftvq`
`WARN  [main] 2017-07-14 06:57:24,122 StartupChecks.java:217 - Directory /cassandra_data/data doesn't exist`
`**ERROR [main] 2017-07-14 06:57:24,162 CassandraDaemon.java:709 - Has no permission to create directory /cassandra_data/data**`

**Comment by lirenjiede** [comment]
It seems that hawkular-cassandra pod have not enough rights to create dir

**Comment by lirenjiede** [comment]
just close issue, due to resolve it.

**Comment by yu2003w** [comment]
How did you resolve the problem?

**Comment by mrmootu** [comment]
How did you resolve the problem?
