### ISSUE TITLE
hawkular-metrics returns 403 Forbidden

### ISSUE THREAD

**Issue by jsuchenia** [openshift/origin-metrics#364]
Recently I installed a fresh cluster using ansible: *openshift-ansible-3.6.173.0.5-2*
Configuration related to metrics and logging applied:
```
#Addons - metrics
openshift_hosted_metrics_deploy=True
openshift_metrics_image_version=v3.6.0

#Addons - logging
openshift_hosted_logging_deploy=True
openshift_metrics_image_version=v3.6.0
```

All hawkular elements are up and running:
![infra_oc_status](https://user-images.githubusercontent.com/10044862/28993599-c96041ae-79ba-11e7-81a4-1ae1b836552c.png)

After project creation any access to PODs, or metrics causing 403 errors:
![hawkular-metrics](https://user-images.githubusercontent.com/10044862/28993592-a06de5ee-79ba-11e7-9983-6e18ca88cc92.png)

Any help how can I troubleshoot it?

**Comment by jsuchenia** [comment]
I checked all the logs, there are no information about authentication.
I even added DEBUG logs via: https://github.com/openshift/origin-metrics/blob/master/docs/hawkular_metrics_advance.adoc

But still, there is no information about authorisation - I believe that it was handled somewhere above the code.

**Comment by jsuchenia** [comment]
After investigation I found that when I have a global *cluster-admin* role - all metics are available and displayed on a page. If I have a credentials only from a project - I'm getting a *403 Forbidden* - so looks like *Hawkular-Tenant* option was not passed/read correctly or validated correctly.

Any hints how can investigate it?

**Comment by kincl** [comment]
I upgraded origin from 1.5 to 3.6 and this started happening for me only for new projects. Existing projects continue to work and metrics are viewable.

**Comment by jsuchenia** [comment]
@kincl could you compare project against each other?  Especially roles assigned to default service account or default per project?

**Comment by kincl** [comment]
@jsuchenia Comparing between a old project from before upgrade and a new project after the upgrade there appears to be no differences in the policyBindings objects. 

It looks like the `openshift-infra/hawkular` service account just has a cluster role binding to be able to view namespaces.

Checked clusterPolicyBindings and I am not sure if this is correct but I have:
```
RoleBinding[hawkular-metrics-admin]:                                                     
                                                                                        Role:                   hawkular-metrics-admin
                                                                                        Users:                  <none>
                                                                                        Groups:                 <none>
                                                                                        ServiceAccounts:        management-infra/management-admin
                                                                                        Subjects:               <none>
RoleBinding[hawkular-namespace-watcher]:                                                 
                                                                                        Role:                   hawkular-metrics
                                                                                        Users:                  <none>
                                                                                        Groups:                 <none>
                                                                                        ServiceAccounts:        openshift-infra/hawkular
```

Kinda strange about `hawkular-metrics-admin` since its clusterPolicy seems to give access to resources that don't exist: hawkular-alerts or hawkular-metrics
```
hawkular-metrics                                                        Verbs                                                           Non-Resource URLs                                                                                                                                       Resource Names                         API Groups                      Resources
                                                                        [get list watch]                                                []                                                                                                                                                      []    []                               [namespaces]
hawkular-metrics-admin                                                  Verbs                                                           Non-Resource URLs                                                                                                                                       Resource Names                         API Groups                      Resources
                                                                        [*]                                                             []                                                                                                                                                      []    []                               [hawkular-alerts hawkular-metrics]
```

**Comment by conatus** [comment]
@jsuchenia 

I am also encountering this issue. I've not upgraded the cluster. Hawkular is running, has the necessary SSL certificates, is throwing the 403 forbidden.

**Comment by conatus** [comment]
In addition to this we have the same behaviour that @jsuchenia is observing - with the `cluster-admin` role a user can view the metrics.

@nicksellen

**Comment by nicksellen** [comment]
It would be great to know which resources it is getting denied for

My best attempt was finding `hawkular-view` rolebinding, and adding myself to it:
```
oc adm policy add-role-to-user view nicksellen -n openshift-infra
```

(I also tried adding the cluster roles `hawkular-metrics` and `hawkular-metrics-admin`, but no difference)

When I list the rolebinding with `oc describe rolebinding hawkular-view` (https://gist.github.com/nicksellen/8fa405d80459613ab4ee47af37d32646)

I can see I am included, and that I can access various resources.

When I make a request for the metrics, such as (authorization header removed):
```
curl -k 'https://$METRICS_DOMAIN/hawkular/metrics/m/stats/query' -H 'Content-Type: application/json' -H 'Hawkular-Tenant: nstest' --data '{"tags":"descriptor_name:network/tx_rate|network/rx_rate|memory/usage|cpu/usage_rate,type:pod,pod_id:d7770cac-9f8c-11e7-a917-06c39c25ba39","bucketDuration":"1mn","start":"-15mn"}'  
```

I get back:
```
<html><head><title>Error</title></head><body>403 - Forbidden</body></html>
```

If I add myself as a `cluster-admin` (or `cluster-reader`) with `oc adm policy add-cluster-role-to-user cluster-admin nicksellen` then all is fine.

I found this nice SubjectAccessReview API call that lets me check which resources I can access (authorization removed...):

```
curl -k -H "Content-Type: application/json" -X POST -d '{"kind":"SubjectAccessReview", "resource": "pods", "verb":"list", "namespace":"openshift-infra"}' https://$MASTER_DOMAIN/oapi/v1/subjectaccessreviews
```

... but again, I don't know which resource to ask for ... would be grateful for any pointers to some useful resources :)

**Comment by nicksellen** [comment]
So, from a hint on https://github.com/openshift/origin/issues/15851 I found that hawkular-metrics itself does the SubjectAccessReview, see https://github.com/hawkular/hawkular-metrics/blob/master/containers/hawkular-openshift-security-filter/src/main/java/org/hawkular/openshift/auth/TokenAuthenticator.java#L256-L259.

I had somehow considered that the authorization was being handled directly by openshift.

**Comment by jsanda** [comment]
I am going to close this issue since it has not had any recent activity. Please feel free to reopen if your issue is unresolved.
