### ISSUE TITLE
Access hawkular metric issue

### ISSUE THREAD

**Issue by ashwinvargh** [openshift/origin-metrics#371]
Hi,

So I am following the documentation and I am able to to access a metric.

curl -k -H "Authorization: Bearer XXXXX" -H "Hawkular-Tenant: hotrod" -X GET https://hawkular-metrics.apps.osh.massopen.cloud/hawkular/metrics/counters/deployment%2Fce5b28bf-7baa-11e7-8017-fa163eb78630%2Fcpu%2Fusage | python -m json.tool

When I try to access the data of the metric in the next step I get a 400 error. 

curl -k -H "Authorization: Bearer XXXX" -H "Hawkular-Tenant: hotrod" -X GET https://hawkular-metrics.apps.osh.massopen.cloud/hawkular/metrics/counters/deployment%2Fce5b28bf-7baa-11e7-8017-fa163eb78630%2Fcpu%2Fusage/data?buckets=5\&start='date -d -10minutes +%s%3N'

<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>

Any help would be great.
Thanks!

**Comment by ashwinvargh** [comment]
So i figured the problem with this command is the start parameter...I just don't know why it doesn't work.

**Comment by jsanda** [comment]
I am going to close this issue since it has not had any recent activity. Please feel free to reopen if your issue is unresolved.
