### ISSUE TITLE
Cassandra's storge usage

### ISSUE THREAD

**Issue by ksemaev** [openshift/origin-metrics#373]
Please advice: documentation says that by default persisted volume claim is specified with the openshift_metrics_cassandra_pvc_size ansible variable which is set to 10 GB

What will happen after this space is used? How long does cassandra stores metrics? How can I clean it up? How can I store it for shorter or longer period? Is it just cleaning up old values when it's storage uses almost all defined space?

I just can't find any information on how to manage this metrics system(

**Comment by jsanda** [comment]
By default metrics have a retention of 7 days. This can be changed with the ```openshift_metrics_duration``` ansible variable. Note that the purging of data does not necessarily happen immediately when we reach 7 days. You will also want to take a look at [capacity planning for cluster metrics](https://docs.openshift.com/container-platform/3.5/scaling_performance/scaling_cluster_metrics.html#scaling-performance-capacity-planning).

**Comment by ksemaev** [comment]
Thank you @jsanda ! Should I create issue in documentation repo for them to specify this info about 7 days?

**Comment by jsanda** [comment]
Sure, if it not already there go ahead.
