### ISSUE TITLE
Metrics tab have not appeared in web-interface

### ISSUE THREAD

**Issue by ksemaev** [openshift/origin-metrics#392]
After installing metrics from ansible role on two separate clusters: the first one was fine, the second one is not showing any metrics tabs in web-interface. Please advice where to dig into?)

**Comment by ksemaev** [comment]
somehow systemctl restart origin-master.service fixes the issue

**Comment by jcantrill** [comment]
This could be that ansible updated the master config file but unsuccessfully restarted the master api service.  The service does not dynamically reload the config
