### ISSUE TITLE
MSC000001: Failed to start service jboss.deployment.subunit."hawkular-metrics.ear"."hawkular-alerts.war".

### ISSUE THREAD

**Issue by tiendungitd** [openshift/origin-metrics#395]
Hi everybody,
I used ansible for deploying metrics in openshift. the status of hawkular-cassandra pod is running and ready state is 1/1. the status of hawkular-metrics pod is runing but the ready state is 0/1.
I get this output from os logs hawkular-metrics, the error is
`ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 72) MSC000001: Failed to start service jboss.deployment.subunit."hawkular-metrics.ear"."hawkular-alerts.war".component.CassCluster.START: org.jboss.msc.service.StartException in service jboss.deployment.subunit."hawkular-metrics.ear"."hawkular-alerts.war".component.CassCluster.START: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance`

see attachment for full log
[hawkular-metrics.log](https://github.com/openshift/origin-metrics/files/1521340/hawkular-metrics.log)

oc version
`oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
`
I install with ansible

`ansible-playbook openshift-ansible/playbooks/byo/openshift-cluster/openshift-metrics.yml \
   -e openshift_metrics_install_metrics=True \
   -e openshift_metrics_hawkular_hostname=metrics.apps.openshift.aavn.local \
   -e openshift_metrics_cassandra_storage_type=dynamic
`
please advise me how to fix it, let me know if you need more information.
Thanks.

**Comment by jsanda** [comment]
I realize that this ticket has been open for a while. Have you retested with a later version? The hawkular-metrics image no longer includes the EAR. It now only deploys a WAR which does **not** include the alerts components referenced in your error message. 

If this is no longer a problem, I would like to close the ticket.

**Comment by jsanda** [comment]
I am going to close this issue since it has not had any recent activity. Please feel free to reopen if your issue is unresolved.
