### ISSUE TITLE
Is there a way to curl metrics without Authorization token in a pod？

### ISSUE THREAD

**Issue by rydeng** [openshift/origin-metrics#407]
I want to curl hawkular-metrics to get metrics in a pod, so is there a way to curl metrics without Authorization token?
just like 
`curl -k -H "Hawkular-Tenant: test" -X GET https://hawkular-metrics.openshift-infra/hawkular/metrics/metrics`

**Comment by jsanda** [comment]
No, you need to use the authorization token. Is it s a problem for you to do so?
