### ISSUE TITLE
How do to deploy metrics components manually in Openshift origin?

### ISSUE THREAD

**Issue by viv816** [openshift/origin-metrics#408]
OpenShit Origin v3.6

How to deploy the metrics components (Heapster, Hawkular, Cassandra) manually in OpenShift Origin?

The metrics components in 'openshift-infra' project somehow got deleted. Is there any procedure to manually deploy through console?

Kindly help.

Thanks.

**Comment by jcantrill** [comment]
3.6 utilizes openshift-ansible.  You should be able to rerun the openshift-metrics role to redeploy these components

**Comment by jsanda** [comment]
@viv816 has your question been answered sufficiently? If so I would like to close this ticket.

**Comment by everflux** [comment]
How about using minishift, I could not find any documented way for that.
