### ISSUE TITLE
Origin-metrics Docker tags: No tag for v3.9.0

### ISSUE THREAD

**Issue by elliothill** [openshift/origin-metrics#423]
OpenShift Origins version: v3.9

I've been using openshift-ansible to deploy an OpenShift Origin platform v3.9. When it comes to deploying the openshift-metrics playbook, the playbook runs through fine but the pods fail with an "ImagePullBackOff" status.

The issue seems to be that the following repositories have three digit tags for all releases except v3.9:

https://store.docker.com/community/images/openshift/origin-metrics-heapster/tags
https://store.docker.com/community/images/openshift/origin-metrics-cassandra/tags
https://store.docker.com/community/images/openshift/origin-metrics-hawkular-metrics/tags

[Edit: This may be the case for all origin-metrics repositories] 

I'm using the "openshift_release=v3.9" variable in my inventory file, and have also tried setting "openshift_image_tag=v3.9" with no success. Ansible will fail with a 2 digit version number, and if openshift_image_tag isn't set, then it automatically falls back to using v3.9.0:

```
TASK [openshift_version : debug] *****************************************************************************
ok: [ehill-os-master.xxx.xxx.xxx] => {
    "msg": "openshift_pkg_version was not defined. Falling back to -3.9.0"
}

TASK [openshift_version : set_fact] *******************************************************************************
ok: [ehill-os-master.xxx.xxx.xxx]

TASK [openshift_version : debug] ********************************************************************************
ok: [ehill-os-master.xxx.xxx.xxx] => {
    "msg": "openshift_image_tag was not defined. Falling back to v3.9.0"
}

TASK [openshift_version : set_fact] ********************************************************************************
ok: [ehill-os-master.xxx.xxx.xxx]

TASK [openshift_version : debug] ********************************************************************************
ok: [ehill-os-master.xxx.xxx.xxx] => {
    "openshift_release": "3.9"
}

TASK [openshift_version : debug] ********************************************************************************
ok: [ehill-os-master.xxx.xxx.xxx] => {
    "openshift_image_tag": "v3.9.0"
}

TASK [openshift_version : debug] ********************************************************************************
ok: [ehill-os-master.xxx.xxx.xxx] => {
    "openshift_pkg_version": "-3.9.0"
}

TASK [openshift_version : debug] ********************************************************************************
ok: [ehill-os-master.xxx.xxx.xxx] => {
    "openshift_version": "3.9.0"
}
```

As there's no v3.9.0 tag in those repositories, the images are failing to be pulled down from docker.io.

Can we please have a v3.9.0 tag to match all previous version formats?

Thanks!

**Comment by d-m** [comment]
I found a [readme in the openshift-ansible repo](https://github.com/openshift/openshift-ansible/tree/release-3.9/roles/openshift_metrics) and I was able to work around this by setting `openshift_metrics_image_version=v3.9` in my inventory file.

**Comment by Talisen** [comment]
Nice spotting! That being said, I think we should be aiming for consistency in our tagging structure, so having a 3.9.0 image tag that is in line with previous versions makes sense. I can't imagine that it would be that hard to create an extra tag for that version?
