### ISSUE TITLE
Exporting data in cassandra

### ISSUE THREAD

**Issue by abhaynayak24** [openshift/origin-metrics#425]
Hi,

Is there any way to export the data that is stored in cassandra database to an excel sheet or mysql? How to access cassandra database as there's no details regarding cassandra access or login specified anywhere.

**Comment by jsanda** [comment]
There is no export feature. You could try using the [copy](https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlshCopy.html) cqlsh command. The cqlsh tool is available in the Cassandra pod.

**Comment by abhaynayak24** [comment]
Hey, thanks @jsanda but I meant, exporting the metrics data that is available in the hawkular-cassandra pod. That will make things easier. I'm trying to fetch the data from the pod as discussed in the forum, but I'm unable to get the metrics values of the pod, Is there some other way to achieve the same?
