### ISSUE TITLE
Metrics startup fails with v3.10 because of missing corresponding images at the docker.io registry

### ISSUE THREAD

**Issue by muehle28** [openshift/origin-metrics#429]
The cluster gets deployed as single-master/multi-nodes with the latest ansible playbook deploy_cluster (https://github.com/openshift/openshift-ansible/tree/release-3.10).

inventory file:
...
openshift_release=v3.10
openshift_image_tag=v3.10.0
...

oc get pods:
NAME                            READY     STATUS             RESTARTS   AGE
hawkular-cassandra-1-l22q6      0/1       ImagePullBackOff   0          35m
hawkular-metrics-lt769          0/1       ImagePullBackOff   0          35m
hawkular-metrics-schema-sh789   0/1       ImagePullBackOff   0          37m
heapster-fshx6                  0/1       ImagePullBackOff   0          35m

The following messages are extracts from the event-log for the according pods:

pulling image "docker.io/openshift/origin-metrics-cassandra:v3.10.0"
Failed to pull image "docker.io/openshift/origin-metrics-cassandra:v3.10.0": rpc error: code = Unknown desc = manifest for docker.io/openshift/origin-metrics-cassandra:v3.10.0 not found

pulling image "docker.io/openshift/origin-metrics-hawkular-metrics:v3.10.0"
Failed to pull image "docker.io/openshift/origin-metrics-hawkular-metrics:v3.10.0": rpc error: code = Unknown desc = manifest for docker.io/openshift/origin-metrics-hawkular-metrics:v3.10.0 not found

pulling image "docker.io/openshift/origin-metrics-schema-installer:v3.10.0"
Failed to pull image "docker.io/openshift/origin-metrics-schema-installer:v3.10.0": rpc error: code = Unknown desc = repository docker.io/openshift/origin-metrics-schema-installer not found: does not exist or no pull access

pulling image "docker.io/openshift/origin-metrics-heapster:v3.10.0"
Failed to pull image "docker.io/openshift/origin-metrics-heapster:v3.10.0": rpc error: code = Unknown desc = manifest for docker.io/openshift/origin-metrics-heapster:v3.10.0 not found

It is possible to work around that for most of the images by specifying the release candidate tag with the following variables:

openshift_metrics_cassandra_image=docker.io/openshift/origin-metrics-cassandra:v3.10.0-rc.0
openshift_metrics_hawkular_metrics_image=docker.io/openshift/origin-metrics-hawkular-metrics:v3.10.0-rc.0
openshift_metrics_heapster_image=docker.io/openshift/origin-metrics-heapster:v3.10.0-rc.0

However, the origin-metrics-schema-installer is not available at all at the docker.io repository.

**Comment by malagant** [comment]
This is still the case after the release of 3.10

**Comment by cjohnston23** [comment]
Any update on this?  The origin-metrics-schema-installer image is still not available.

**Comment by aramalipoor** [comment]
\cc @jsanda @smarterclayton

**Comment by aramalipoor** [comment]
Any updates on `v3.10.0` image tags?

**Comment by isaldarriaga** [comment]
same error for a number of pods in the openshift-logging namespace:

```
"docker.io/openshift/origin-logging-fluentd:v3.10.0": rpc error: code = Unknown desc = manifest for docker.io/openshift/origin-logging-fluentd:v3.10.0 not found

Failed to pull image "docker.io/openshift/origin-logging-auth-proxy:v3.10.0": rpc error: code = Unknown desc = manifest for docker.io/openshift/origin-logging-auth-proxy:v3.10.0 not found

Failed to pull image "docker.io/openshift/origin-logging-kibana:v3.10.0": rpc error: code = Unknown desc = manifest for docker.io/openshift/origin-logging-kibana:v3.10.0 not found

```

**Comment by jfcoz** [comment]
It's maybe related to this pending jenkins job : https://ci.openshift.redhat.com/jenkins/job/push_origin_metrics_release_310/ ?

**Comment by cjohnston23** [comment]
I was able to find a workaround for this issue, by using the following image from dockerhub.

docker.io/alv91/origin-metrics-schema-installer:latest

I updated the hawkular-metrics-schema pod with the above image and the job completed and hawkular and heapster pods then started.

**Comment by alv91** [comment]
@cjohnston23 I builded origin-metrics with [this repo](https://github.com/openshift/origin-metrics/tree/release-3.10/schema-installer), switching to HAWKULAR_METRICS_VERSION="0.30.5.Final". 

There is an issue, metrics are visible only on POD view. If you try to get metrics on eg. deplyment tab, you will get
>Failed to perform operation due to an error: OnError while emitting onNext value: org.hawkular.metrics.model.Metric.class

EDIT:
I can confirm, that with `openshift/origin-metrics-hawkular-metrics:v3.11` and `alv91/origin-metrics-schema-installer:3.10` problem from above does not exist.

**Comment by jkroepke** [comment]
@jsanda Can you re-check this? 

https://github.com/openshift/origin-metrics/issues/429#issuecomment-414948369

**Comment by hirenvadalia** [comment]
Any update on this? I am also facing this issue while deploying OKD 3.10 with metrics.

**Comment by jkroepke** [comment]
My working solution:

```
# https://github.com/openshift/origin-metrics/issues/429
openshift_metrics_cassandra_image: "docker.io/openshift/origin-metrics-cassandra:v3.11.0"
openshift_metrics_hawkular_metrics_image: "docker.io/openshift/origin-metrics-hawkular-metrics:v3.11.0"
openshift_metrics_heapster_image: "docker.io/openshift/origin-metrics-heapster:v3.11.0"
# https://github.com/openshift/origin-metrics/issues/429#issuecomment-417124646
openshift_metrics_schema_installer_image: "docker.io/alv91/origin-metrics-schema-installer:v3.10.0"
```

**Comment by hirenvadalia** [comment]
@jkroepke Thank a lots for confirming, I just see this comments and I am trying deployment with this changes in inventory

**Comment by morsik** [comment]
This problem still exists, and @jkroepke solution works (but obviously this is different version… not-stable yet probably since 3.11 is not released yet?)

**Comment by netoralves** [comment]
For me works with this two directives in [OSEv3:vars]:

package_version=3.10
openshift_image_tag=v3.10.0-rc.0

**Comment by ThoTischner** [comment]
My working solution for upgrade path from 3.9 to 3.11:
```
ansible-playbook /usr/local/src/openshift-ansible/playbooks/openshift-metrics/config.yml -e ansible_ssh_user=foo -e openshift_image_tag=v3.10.0-rc.0 -K -T 60
```
