### ISSUE TITLE
hawkular-alerts not in openshift 3.9

### ISSUE THREAD

**Issue by fanfanbj** [openshift/origin-metrics#430]
I am trying openshift3.9, which use openshift3/metrics-hawkular-metrics:v3.9.27.

When I curl /hawkular/alerts API, I got 404. 

Then I downgrade to openshift3/metrics-hawkular-metrics:v3.7.46, I can curl /hawkular/alerts API successfully. 

So I guess the newer version will without alerts module.

**Comment by maidirepelle** [comment]
@fanfanbj your guess is right. Take a look at https://docs.openshift.com/container-platform/3.9/release_notes/ocp_3_9_release_notes.html . As reported from https://bugzilla.redhat.com/show_bug.cgi?id=1543647 , they removed alerts from hawkular metrics bundle included in OCP starting version 3.9
