### ISSUE TITLE
service account not found error

### ISSUE THREAD

**Issue by shilpapadgaonkar** [openshift/origin-metrics#49]
Hello,
Since we faced an issue https://github.com/kubernetes/heapster/issues/658, we decided to upgrade our old installation. I noticed that you are now using your own heapster image. I followed the installation manual and this leads to the hawkular pod going in pending state  forever. When i do describe rc for hawkular metrics, it shows me the following error 
Error creating: Pod "hawkular-metrics-" is forbidden: service account cmetrics/hawkular was not found, retry after the service account is created

Kindly help.

Regards,
Shilpa

**Comment by mwringe** [comment]
Hmm, the hawkular service account should have been created as part of the installation: https://github.com/openshift/origin-metrics/blob/master/deployer/templates/support.yaml#L16

How did you perform the install?

**Comment by shilpapadgaonkar** [comment]
yes you are right, its a part of the installation and those service accounts exist too. Hence I dont know why this error occurs.

**Comment by mwringe** [comment]
But does the service accounts exist for this 'cmetrics' project or is it under some other project? Its weird to get that error if the service account already exists.

**Comment by shilpapadgaonkar** [comment]
yes it does exist for cmetrics project

**Comment by mwringe** [comment]
Can you provide any more information over how exactly you performed the installation? Right now this is a bit confusing to me as I can't figure out why it would be complaining about a service account if it already exists.

**Comment by shilpapadgaonkar** [comment]
I followed your documentation exactly as provided here https://github.com/openshift/origin-metrics.
We have built the images locally. The only change I had to do was access heapster in a insecure way because I am using the enterprise version 3.0.2. However this workaround has been tested by me in a previous install and it worked fine.

We have an older version of this (heapster, hawkular, cassandra )stack running in our env. This was deployed without any issues.
The reason we wanted to upgrade is that the heapster version used there produces null pointer exception and keeps restarting whenever kubelet sends it empty stats. The issue is described here -- 

https://github.com/kubernetes/heapster/issues/682

**Comment by mwringe** [comment]
Are you sure the Hawkular Metrics component is not started and the error about the service account not existing is not just an old message?

Do you get any output from performing 'oc logs' on the Hawkular Metrics component?

**Comment by mwringe** [comment]
Any update on this? Still waiting to see if the issue has to do with something about the service account, or if that error is not what the main problem is.

**Comment by shilpapadgaonkar** [comment]
yes it was not an old message. I tried it several times. So we are now upgrading our env to 3.1 and then hopefully this should work. I will come back if I face similar or other issues on 3.1

Thanks

**Comment by mwringe** [comment]
Housekeeping to close older issues. If you think this issue is not resolved, please reopen it.
