### ISSUE TITLE
Create diagnostic tool

### ISSUE THREAD

**Issue by mwringe** [openshift/origin-metrics#54]
The deployment and installation can be at times a bit tricky. We should provide some sort of mechanism above the Hawkular Metrics /status and Heapster's /validate endpoints for checking that things are properly installed and running correctly.

When https://issues.jboss.org/browse/HWKMETRICS-325 is completed, it may also be something we need to document or expose for people to use as verification.

**Comment by jcantrill** [comment]
@sosiouxme is this satisfied by https://trello.com/c/7VTcGrMB/226-5-metrics-validations-diagnostics-hawkular  .  Do we need to provide additional documentation?

**Comment by mwringe** [comment]
Closing this issue as we now have this as part of the deployer.
