### ISSUE TITLE
Building heapster-base fails. 

### ISSUE THREAD

**Issue by ivanthelad** [openshift/origin-metrics#55]
Building the heapster-base image fails on "go get -d k8s.io/heapster"

[root@gitlab orig]# git clone https://github.com/openshift/origin-metrics.git
Cloning into 'origin-metrics'...
remote: Counting objects: 263, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 263 (delta 5), reused 0 (delta 0), pack-reused 246
Receiving objects: 100% (263/263), 229.12 KiB | 0 bytes/s, done.
Resolving deltas: 100% (135/135), done.
[root@gitlab orig]# cd origin-metrics/
[root@gitlab origin-metrics]# docker build heapster-base
Sending build context to Docker daemon 3.072 kB
Step 0 : FROM centos:centos7
 ---> ce20c473cd8a
Step 1 : MAINTAINER Hawkular Metrics <hawkular-dev@lists.jboss.org>
 ---> Using cache
 ---> 2931e709de94
Step 2 : EXPOSE 8082
 ---> Using cache
 ---> 411ea865a710
Step 3 : ENV HEAPSTER_COMMIT af4752e
 ---> Running in 6c6b38d6a564
 ---> 5377cdf18dbd
Removing intermediate container 6c6b38d6a564
Step 4 : RUN yum install -y -q go git wget make &&     yum clean all &&     export GOPATH=/tmp/gopath &&     export PATH=$PATH:$GOPATH/bin &&     mkdir -p $GOPATH &&     cd $GOPATH &&     go get -d k8s.io/heapster &&     cd src/k8s.io/heapster &&     git checkout $HEAPSTER_COMMIT &&     make &&     cp heapster /opt &&     rm -rf $GOPATH &&     yum remove -y -q go git wget make
 ---> Running in e21912e46003
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
warning: /var/cache/yum/x86_64/7/base/packages/fipscheck-1.4.1-5.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Public key for fipscheck-1.4.1-5.el7.x86_64.rpm is not installed
Public key for glibc-common-2.17-106.el7_2.1.x86_64.rpm is not installed
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-1.1503.el7.centos.2.8.x86_64 (@CentOS)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
install-info: No such file or directory for /usr/share/info/wget.info.gz
Loaded plugins: fastestmirror
Cleaning repos: base extras systemdcontainer updates
Cleaning up everything
Cleaning up list of fastest mirrors
package k8s.io/heapster
	imports github.com/bigdatadev/goryman
	imports github.com/golang/protobuf/proto
	imports github.com/coreos/etcd/client
	imports github.com/coreos/fleet/client
	imports github.com/coreos/fleet/pkg
	imports github.com/coreos/fleet/registry
	imports github.com/emicklei/go-restful
	imports github.com/golang/glog
	imports github.com/google/cadvisor/client
	imports github.com/google/cadvisor/info/v1
	imports github.com/hawkular/hawkular-client-go/metrics
	imports github.com/influxdb/influxdb/client
	imports github.com/optiopay/kafka
	imports github.com/optiopay/kafka/proto
	imports github.com/golang/snappy
	imports google.golang.org/cloud/compute/metadata
	imports golang.org/x/net/context
	imports k8s.io/kubernetes/pkg/api
	imports github.com/davecgh/go-spew/spew
	imports github.com/ghodss/yaml
	imports gopkg.in/yaml.v2
	imports github.com/google/gofuzz
	imports github.com/ugorji/go/codec
	imports k8s.io/kubernetes/pkg/api/unversioned
	imports k8s.io/kubernetes/pkg/fields
	imports k8s.io/kubernetes/pkg/labels
	imports k8s.io/kubernetes/pkg/api/resource
	imports github.com/spf13/pflag
	imports speter.net/go/exp/math/dec/inf
	imports k8s.io/kubernetes/pkg/auth/user
	imports k8s.io/kubernetes/pkg/util
	imports github.com/docker/libcontainer/cgroups/fs
	imports github.com/docker/docker/pkg/mount
	imports github.com/docker/docker/pkg/units
	imports github.com/docker/docker/pkg/units
	imports github.com/docker/docker/pkg/units: cannot find package "github.com/docker/docker/pkg/units" in any of:
	/usr/lib/golang/src/github.com/docker/docker/pkg/units (from $GOROOT)
	/tmp/gopath/src/github.com/docker/docker/pkg/units (from $GOPATH)
The command '/bin/sh -c yum install -y -q go git wget make &&     yum clean all &&     export GOPATH=/tmp/gopath &&     export PATH=$PATH:$GOPATH/bin &&     mkdir -p $GOPATH &&     cd $GOPATH &&     go get -d k8s.io/heapster &&     cd src/k8s.io/heapster &&     git checkout $HEAPSTER_COMMIT &&     make &&     cp heapster /opt &&     rm -rf $GOPATH &&     yum remove -y -q go git wget make' returned a non-zero code: 1

**Comment by ivanthelad** [comment]
issue due to docker changing their package structure... that package doesn't exist in master any more

**Comment by mwringe** [comment]
Cannot reproduce. The Heapster Base image can be built without issue for me.

**Comment by ivanthelad** [comment]
yes, seems at the time this occured there was some re-org in package strcuture. it doesn't occur for me either.  this can be closed
