### ISSUE TITLE
No metrics shown for certain tenants

### ISSUE THREAD

**Issue by shilpapadgaonkar** [openshift/origin-metrics#64]
Hello @mwringe 

We do not get metrics for certain tenants in our env. Also  for _system tenant we get 

curl -H "Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" -H "Hawkular-tenant: _system" -X GET https://xxx.xxx.xx.xx/hawkular/metrics/metrics --insecure | python -m json.tool

No JSON object could be decoded

Regards,
Shilpa

**Comment by shilpapadgaonkar** [comment]
Probably its ---- https://github.com/openshift/origin-metrics/issues/62

**Comment by mwringe** [comment]
yeah, I would suspect if you ran that command without the `| python -m json.tool` it would be returning no values, this is probably due to Heapster not populating Hawkular Metrics with anything.
