### ISSUE TITLE
heapster network metrics

### ISSUE THREAD

**Issue by priyanka5** [openshift/origin-metrics#66]
Hi,

are network metrics available at project or pod level?? I tried getting network metrics for a pod but it returns:

No JSON object could be decoded 

Thanks,
Yash

**Comment by mwringe** [comment]
No, not yet, we are waiting for https://github.com/kubernetes/heapster/pull/749 to be merged first.

**Comment by mwringe** [comment]
Housekeeping to close older issues. If you think this issue is not resolved, please reopen it.
