### ISSUE TITLE
Query to get only active projects/tenants from hawkular

### ISSUE THREAD

**Issue by shilpapadgaonkar** [openshift/origin-metrics#71]
Hello,
I am currently using https://hawkular-service/hawkular/metrics/tenants to get a list of all tenants/projects in the openshift env. 
The response I get also includes projects that have been deleted (or which are not active in terms of openshift). Could you kindly let me know how to change this query to get only the active projects?

Thanks,
Shilpa

**Comment by mwringe** [comment]
Hawkular Metrics currently only keeps track of metrics and not the state of projects in OpenShift. The best way to determine a project's status would be to query OpenShift directly (https://docs.openshift.org/latest/rest_api/index.html or via one of the kubernetes client tools)

**Comment by mwringe** [comment]
Housekeeping to close older issues. If you think this issue is not resolved, please reopen it.
