### ISSUE TITLE
UnknownHostException for service 'hawkular-cassandra-nodes'

### ISSUE THREAD

**Issue by sjenning** [openshift/origin-metrics#72]
Running metrics-deployer template like this:
```
oc process -f metrics-deployer.yaml -v HAWKULAR_METRICS_HOSTNAME=hawkular.apps.variantweb.net,USE_PERSISTENT_STORAGE=false | oc create -f -
```

Pod hawkular-cassandra-1-ys1sm fails with:

```
UnknownHostException for service 'hawkular-cassandra-nodes'. It may not be up yet. Trying again
```

End state looks like this:

```
# oc get all
CONTROLLER                   CONTAINER(S)                   IMAGE(S)                                                     SELECTOR                              REPLICAS                  AGE
hawkular-cassandra-1         hawkular-cassandra-1           docker.io/openshift/origin-metrics-cassandra:latest          name=hawkular-cassandra-1             1                         10m
hawkular-metrics             hawkular-metrics               docker.io/openshift/origin-metrics-hawkular-metrics:latest   name=hawkular-metrics                 1                         10m
heapster                     heapster                       docker.io/openshift/origin-metrics-heapster:latest           name=heapster                         1                         10m
NAME                         HOST/PORT                      PATH                                                         SERVICE                               LABELS                    INSECURE POLICY   TLS TERMINATION
hawkular-metrics             hawkular.apps.variantweb.net                                                                hawkular-metrics                      metrics-infra=support                       passthrough
NAME                         CLUSTER_IP                     EXTERNAL_IP                                                  PORT(S)                               SELECTOR                  AGE
hawkular-cassandra           172.30.56.107                  <none>                                                       9042/TCP,9160/TCP,7000/TCP,7001/TCP   type=hawkular-cassandra   10m
hawkular-cassandra-nodes     None                           <none>                                                       9042/TCP,9160/TCP,7000/TCP,7001/TCP   type=hawkular-cassandra   10m
hawkular-metrics             172.30.101.166                 <none>                                                       443/TCP                               name=hawkular-metrics     10m
heapster                     172.30.89.20                   <none>                                                       80/TCP                                name=heapster             10m
NAME                         READY                          STATUS                                                       RESTARTS                              AGE
hawkular-cassandra-1-ys1sm   0/1                            Error                                                        0                                     10m
hawkular-metrics-p6f5l       0/1                            Pending                                                      0                                     10m
heapster-i6xcb               0/1                            Pending                                                      0                                     10m
```

Of note, the hawkular-cassandra-nodes has no cluster IP, as per the ```portalIp: None``` in the service definition.

Should ```CASSANDRA_NODES_SERVICE_NAME="hawkular-cassandra"``` in the cassandra/Dockerfile?

**Comment by mwringe** [comment]
The Cassandra pod should not be failing with:

`UnknownHostException for service 'hawkular-cassandra-nodes'. It may not be up yet. Trying again`

Its not an error condition but a check that its trying to perform.

You should be seeing another error in the Cassandra logs about why it could not be started

**Comment by sjenning** [comment]
@mwringe Here is the whole ```oc logs``` output from the failed pod

http://fpaste.org/318181/14545326/

I don't see anything that indicates a fatal error but maybe I just can't see it.

**Comment by mwringe** [comment]
Well that is no good, there is no fatal error at all in those logs. I suspect that would mean the Cassandra didn't fail on its own and that something else killed it, but I am not sure what exactly would have killed it.

We do have a ready script, but its shouldn't be killing the container like this.

If you do `oc describe pod hawkular-cassandra-1-ys1sm` does any useful information get displayed? There might be something in the events list.

If possible, could you disable the postStart script in the Cassandra replication controller? That may help us rule that out as being a problem.

**Comment by sjenning** [comment]
@mwringe thanks for looking at this.  I redeployed my origin cluster using official packages and everything deployed ok.  I'm thinking this is user error, though I'm not sure exactly what my error was.  Either way, can't recreate now.

**Comment by mwringe** [comment]
@sjenning if you run into the problem again, please let us know. It can be tricky to figure out why things fail sometimes, especially with no obvious error messages in the logs.
