### ISSUE TITLE
Heapster 0.19.x 

### ISSUE THREAD

**Issue by git001** [openshift/origin-metrics#78]
Hi.

We have tried to use heapster 0.19.1 with influxdb 0.10 on ose.

I have described the setup in heapster.

https://github.com/kubernetes/heapster/issues/977

have you any plans to use 0.19.x in openshift?

**Comment by mwringe** [comment]
The current version is based on the `heapster-scalability` branch and I believe it's version is 0.20.x

**Comment by git001** [comment]
for origin, right.
Do you have tried to use this version with the enterprise version?
We was not able to read any data with service account activated.

**Comment by mwringe** [comment]
This github issue tracker is only meant for the origin containers. Issues with the enterprise versions are usually handled in https://bugzilla.redhat.com/

There will be an update to 0.20 (or newer) in the future for the enterprise version, this is currently planned for a release after 3.3

**Comment by git001** [comment]
Okay thanks.

**Comment by mwringe** [comment]
A quick correction, It should be out for the 3.3 release, not after the 3.3 release
