### ISSUE TITLE
Please provide enterprise variants of the deployer template

### ISSUE THREAD

**Issue by sdodson** [openshift/origin-metrics#80]
Currently we pull the deployer template into openshift-ansible and the sync script there copies the origin content for enterprise. It'd be helpful if an enterprise deployer template were maintained in your repo so that the productization team no longer needs to carefully review the diffs each time. Right now the diff is just the IMAGE_PREFIX and IMAGE_VERSION which are set to 'registry.access.redhat.com/openshift3/' and '3.1.1' respectively for the enterprise version but perhaps there are other differences that would be better maintained by the subject matter experts rather than the installer folks.

See https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/examples-sync.sh#L42-L43

**Comment by mwringe** [comment]
There is now an enterprise template available under the 'enterprise' branch: https://github.com/openshift/origin-metrics/tree/enterprise

We will be tagging these with 'ose-v1.x'. Currently there is already tags for 'ose-v1.1' and 'ose-v1.2'.

Does this fit your use case here? Or are other modifications required?

**Comment by sdodson** [comment]
That should be good, thanks!

**Comment by jcantrill** [comment]
closing based upon https://github.com/openshift/origin-metrics/issues/80#issuecomment-211600799
