### ISSUE TITLE
Heapster doesn't update metrics in hawkular sink

### ISSUE THREAD

**Issue by jdnieto** [openshift/origin-metrics#83]
I've deployed through metrics-deployer template heapster and hawkular. It creates 3 pods with a running state and no error in logs. However, in the OpenShift web console, graphics from metrics are empty. If I access to heapster via API Proxy I'm able to see metrics, but when I access to hawkular the information is not updated.

**Comment by mwringe** [comment]
Can you verify that you are seeing actual metrics values in the Heapster api and not just that metrics are being created?

Normally when you see empty charts in the console its due to a certificate issue (https://github.com/openshift/origin-metrics/blob/master/docs/troubleshooting.adoc#empty-charts)

**Comment by jdnieto** [comment]
@mwringe you are right, the metrics I saw are those when heapster was created.
Node and Master certificates are populated with IP and DNS. But the same result.
I "tcpdumped" the network and saw that heapster is pushing to hawkular, but in the logs I saw something like that
```
I0223 06:20:56.610346       1 impl.go:398] Model Update operation started
I0223 06:20:56.610760       1 impl.go:434] Schema Update operation completed
I0223 06:20:57.472444       1 external.go:116] no timeseries data between 2016-02-23 11:11:36.444952886 +0000 UTC and 0001-01-01 00:00:00 +0000 UTC
I0223 06:20:57.472701       1 external.go:138] Storing Timeseries to "Hawkular-Metrics Sink"
I0223 06:20:57.472746       1 external.go:142] Storing Events to "Hawkular-Metrics Sink"
I0223 06:21:07.473233       1 external.go:116] no timeseries data between 2016-02-23 11:11:36.444952886 +0000 UTC and 0001-01-01 00:00:00 +0000 UTC
I0223 06:21:07.473475       1 external.go:138] Storing Timeseries to "Hawkular-Metrics Sink"
I0223 06:21:07.473514       1 external.go:142] Storing Events to "Hawkular-Metrics Sink"
I0223 06:21:17.474500       1 external.go:116] no timeseries data between 2016-02-23 11:11:36.444952886 +0000 UTC and 0001-01-01 00:00:00 +0000 UTC
I0223 06:21:17.474751       1 external.go:138] Storing Timeseries to "Hawkular-Metrics Sink"
I0223 06:21:17.474800       1 external.go:142] Storing Events to "Hawkular-Metrics Sink"
```
Any clue about that?

**Comment by mwringe** [comment]
Can you provide some information about your setup (OpenShift version, origin-metrics container versions) and what configuration options were used when deploying origin-metrics?

**Comment by Coyote5** [comment]
Hi @jdnieto, I have the same problem. Have you solved your problem?

**Comment by Coyote5** [comment]
Hi @mwringe, my openshift and origin-metrics version:
```
openshift v1.2.1
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5

origin-metrics contrainter version: v1.2.1
