### ISSUE TITLE
Alerts in Hawkular

### ISSUE THREAD

**Issue by jdnieto** [openshift/origin-metrics#84]
Hi, I'm wondering if it is possible to create and acces to hawkular alerts in openshift.
I'm trying this request but is not working
```
 curl --insecure --silent --header "Authorization: Bearer $BEARER" --header "Hawkular-Tenant: _system" --request GET https://hawkular-metrics.example.com/hawkular/alerts
```
The response is a `HTTP Status 404 - /hawkular/alerts` `The requested resource is not available.`

**Comment by mwringe** [comment]
Currently we only have Hawkular Metrics containers running here without Hawkular Alerts. There is a plan to get Hawkular Alerts added as well but it will not be until at least after the next release.

We do not have the full Hawkular project as part of origin-metrics, only the Hawkular Metrics part of it.

**Comment by jdnieto** [comment]
Thanks.

**Comment by cgutshal** [comment]
@mwringe Is the plan for adding the alerts being tracked at this time?

**Comment by mwringe** [comment]
@cgutshal The Hawkular Metrics EAR now includes alerting :) So there is alerting in the ear and instructions for how to use it can be found here: https://github.com/openshift/origin-metrics/blob/master/docs/hawkular_metrics.adoc#accessing-metrics-using-hawkular-metrics

Unfortunately its not tied into any UI at the moment, and you would have to access it via REST only for now.

**Comment by cgutshal** [comment]
Awesome appreciate the info @mwringe

**Comment by theute** [comment]
May I ask what kind of alert you would want to setup ?
What conditions and what actions  ?
