### ISSUE TITLE
e2e test failure at checkDeployer when deployer image is already downloaded

### ISSUE THREAD

**Issue by vnugent** [openshift/origin-metrics#92]
On a fast system or when metrics-deployer docker image already downloaded the pod state may not be in `Pending`
https://github.com/openshift/origin-metrics/blob/master/hack/tests/test_default_deploy.sh#L29

The following tweak seemed to get the test going
```bash
if [[ $state == "Pending" ]] || [[ $state == "Completed" ]] || [[ $state == "Running" ]]; then
```

**Comment by mwringe** [comment]
Its been fixed with the latest commit.
