### ISSUE TITLE
documentation refers to incorrect storage access mode based on PVC in template

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin-metrics#98]
Since the template is requesting a RWX/RWO PV, and the documentation says you only need an RWO PV, the PVC will fail to claim.

The PVC should have RWX removed, or the docs should be updated to specify RWX.

**Comment by mwringe** [comment]
Where are you seeing RWX?
See https://github.com/openshift/origin-metrics/blob/master/deployer/templates/hawkular-cassandra-node-pv.yaml#L40

**Comment by thoraxe** [comment]
It's here:

https://docs.openshift.com/enterprise/latest/install_config/cluster_metrics.html#metrics-persistent-storage

Which I assumed was pulled from the docs for this. But I checked the README for this repo and it is not indicated. So I will close this in favor of a docs bug.

**Comment by thoraxe** [comment]
https://github.com/openshift/openshift-docs/issues/1842
